-- Organization, MBO, RACI work ownership, and attendance calendar

create table if not exists public.org_units (
  id bigint generated by default as identity primary key,
  name text not null,
  unit_type text not null default 'team' check (unit_type in ('company', 'division', 'department', 'team')),
  parent_id bigint references public.org_units(id) on delete set null,
  manager_member_id bigint references public.members(id) on delete set null,
  description text not null default '',
  sort_order integer not null default 0,
  active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (parent_id, name)
);

create table if not exists public.member_role_profiles (
  id bigint generated by default as identity primary key,
  member_id bigint not null unique references public.members(id) on delete cascade,
  org_unit_id bigint references public.org_units(id) on delete set null,
  job_title text not null default '',
  role_summary text not null default '',
  responsibilities text[] not null default '{}',
  authority_scope text not null default '',
  updated_at timestamptz not null default now()
);

create table if not exists public.mbo_objectives (
  id bigint generated by default as identity primary key,
  member_id bigint not null references public.members(id) on delete cascade,
  org_unit_id bigint references public.org_units(id) on delete set null,
  year integer not null check (year between 2020 and 2100),
  title text not null,
  description text not null default '',
  metric text not null default '',
  target_value text not null default '',
  current_value text not null default '',
  weight numeric(5,2) not null default 0 check (weight between 0 and 100),
  progress integer not null default 0 check (progress between 0 and 100),
  status text not null default 'planned' check (status in ('planned', 'in_progress', 'at_risk', 'completed', 'hold')),
  due_date date,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.work_responsibilities (
  id bigint generated by default as identity primary key,
  org_unit_id bigint references public.org_units(id) on delete set null,
  title text not null,
  description text not null default '',
  output_definition text not null default '',
  cycle text not null default '',
  active boolean not null default true,
  sort_order integer not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.responsibility_assignments (
  id bigint generated by default as identity primary key,
  responsibility_id bigint not null references public.work_responsibilities(id) on delete cascade,
  member_id bigint not null references public.members(id) on delete cascade,
  assignment_type text not null check (assignment_type in ('R', 'A', 'C', 'I')),
  created_at timestamptz not null default now(),
  unique (responsibility_id, member_id, assignment_type)
);

create table if not exists public.attendance_events (
  id bigint generated by default as identity primary key,
  member_id bigint not null references public.members(id) on delete cascade,
  event_type text not null check (event_type in ('annual_leave', 'am_half', 'pm_half', 'quarter_day', 'vacation', 'business_trip', 'outside_work', 'holiday_work')),
  start_date date not null,
  end_date date not null,
  start_time time,
  end_time time,
  unit_days numeric(4,2) not null default 1 check (unit_days > 0 and unit_days <= 31),
  note text not null default '',
  status text not null default 'confirmed' check (status in ('requested', 'confirmed', 'cancelled')),
  created_by uuid default auth.uid() references auth.users(id) on delete set null,
  source_schedule_id bigint unique references public.schedules(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  check (end_date >= start_date)
);

create index if not exists idx_org_units_parent on public.org_units(parent_id, sort_order);
create unique index if not exists org_units_parent_name_unique
  on public.org_units (coalesce(parent_id, 0), lower(name));
create index if not exists idx_role_profiles_org on public.member_role_profiles(org_unit_id);
create index if not exists idx_mbo_member_year on public.mbo_objectives(member_id, year);
create index if not exists idx_responsibilities_org on public.work_responsibilities(org_unit_id, sort_order);
create index if not exists idx_assignments_responsibility on public.responsibility_assignments(responsibility_id);
create index if not exists idx_attendance_dates on public.attendance_events(start_date, end_date);
create index if not exists idx_attendance_member_dates on public.attendance_events(member_id, start_date, end_date);

-- Seed the current departments and job titles without overwriting future edits.
insert into public.org_units (name, unit_type, sort_order)
select department_name, 'team', row_number() over (order by department_name)
from (
  select distinct trim(department) as department_name
  from public.members
  where coalesce(trim(department), '') <> ''
) departments
on conflict (parent_id, name) do nothing;

insert into public.member_role_profiles (member_id, org_unit_id, job_title)
select m.id, ou.id, coalesce(m.position, '')
from public.members m
left join public.org_units ou on ou.name = trim(m.department) and ou.parent_id is null
on conflict (member_id) do nothing;

-- Move legacy personal schedule records into the dedicated attendance model.
insert into public.attendance_events (
  member_id, event_type, start_date, end_date, start_time, unit_days, note,
  status, created_by, source_schedule_id
)
select
  m.id,
  case s.type
    when '연차' then 'annual_leave'
    when '오전반차' then 'am_half'
    when '오후반차' then 'pm_half'
    when '반반차' then 'quarter_day'
    when '휴가' then 'vacation'
    when '출장' then 'business_trip'
    when '외근' then 'outside_work'
    when '휴일근로' then 'holiday_work'
  end,
  nullif(s.date, '')::date, nullif(s.date, '')::date, nullif(s.time, '')::time,
  case when s.type in ('오전반차', '오후반차') then 0.5 when s.type = '반반차' then 0.25 else 1 end,
  coalesce(s.content, ''), 'confirmed', m.auth_id, s.id
from public.schedules s
join public.members m on trim(m.name) = trim(s.target)
where s.type in ('연차', '오전반차', '오후반차', '반반차', '휴가', '출장', '외근', '휴일근로')
  and m.auth_id is not null
  and s.date ~ '^\d{4}-\d{2}-\d{2}$'
on conflict (source_schedule_id) do nothing;

alter table public.org_units enable row level security;
alter table public.member_role_profiles enable row level security;
alter table public.mbo_objectives enable row level security;
alter table public.work_responsibilities enable row level security;
alter table public.responsibility_assignments enable row level security;
alter table public.attendance_events enable row level security;

do $$
declare table_name text;
begin
  foreach table_name in array array[
    'org_units', 'member_role_profiles', 'mbo_objectives',
    'work_responsibilities', 'responsibility_assignments'
  ] loop
    execute format('drop policy if exists %I on public.%I', table_name || '_read_members', table_name);
    execute format(
      'create policy %I on public.%I for select to authenticated using ((select private.is_nexus_member()))',
      table_name || '_read_members', table_name
    );
    execute format('drop policy if exists %I on public.%I', table_name || '_admin_all', table_name);
    execute format(
      'create policy %I on public.%I for all to authenticated using ((select private.is_nexus_admin())) with check ((select private.is_nexus_admin()))',
      table_name || '_admin_all', table_name
    );
  end loop;
end $$;

drop policy if exists attendance_read_members on public.attendance_events;
create policy attendance_read_members on public.attendance_events
for select to authenticated
using ((select private.is_nexus_member()));

drop policy if exists attendance_insert_self_or_admin on public.attendance_events;
create policy attendance_insert_self_or_admin on public.attendance_events
for insert to authenticated
with check (
  (select private.is_nexus_admin())
  or exists (
    select 1 from public.members m
    where m.id = member_id and m.auth_id = (select auth.uid())
  )
);

drop policy if exists attendance_update_self_or_admin on public.attendance_events;
create policy attendance_update_self_or_admin on public.attendance_events
for update to authenticated
using (
  (select private.is_nexus_admin())
  or exists (
    select 1 from public.members m
    where m.id = member_id and m.auth_id = (select auth.uid())
  )
)
with check (
  (select private.is_nexus_admin())
  or exists (
    select 1 from public.members m
    where m.id = member_id and m.auth_id = (select auth.uid())
  )
);

drop policy if exists attendance_delete_self_or_admin on public.attendance_events;
create policy attendance_delete_self_or_admin on public.attendance_events
for delete to authenticated
using (
  (select private.is_nexus_admin())
  or exists (
    select 1 from public.members m
    where m.id = member_id and m.auth_id = (select auth.uid())
  )
);

revoke all on public.org_units, public.member_role_profiles, public.mbo_objectives,
  public.work_responsibilities, public.responsibility_assignments, public.attendance_events from anon;
grant select, insert, update, delete on public.org_units, public.member_role_profiles,
  public.mbo_objectives, public.work_responsibilities, public.responsibility_assignments,
  public.attendance_events to authenticated;
grant usage, select on sequence public.org_units_id_seq,
  public.member_role_profiles_id_seq, public.mbo_objectives_id_seq,
  public.work_responsibilities_id_seq, public.responsibility_assignments_id_seq,
  public.attendance_events_id_seq to authenticated;
