-- ============================================================
-- Harim Nexus 스키마 (2026-09-29, 완전 리빌드)
--
-- 대상: 기존 Supabase 프로젝트(hvjtsxaztavskhvexnct). public 스키마(기말재고 등)는 건드리지 않고
--       넥서스 표는 harim_nexus, 권한 확인용 내부 함수는 harim_nexus_private 스키마에 만든다.
-- 실행: SQL Editor 에 이 파일 전체를 붙여 넣고 한 번 실행한다. 데이터는 넣지 않는다.
-- 실행 후: Project Settings > Data API > Exposed schemas 에 harim_nexus 추가
--          (harim_nexus_private 은 추가하지 말 것 — 외부에서 호출되면 안 되는 함수들이다)
--
-- 기존 마이그레이션(supabase/migrations/*)을 순서대로 합친 것이며 다음은 뺐다:
--   - snop-mgt 전용 handle_new_user 트리거 함수
--   - 'crusade153' 관리자 지정 (관리자는 scripts/seed-admin.mjs 로 만든다)
--   - 옛 데이터 이관용 seed insert
-- ============================================================

create extension if not exists pgcrypto with schema extensions;

create schema if not exists harim_nexus;
grant usage on schema harim_nexus to anon, authenticated, service_role;


-- ============================================================
-- 1. 기본 테이블 (members, projects, tasks, posts, comments, archives, schedules, quick_links, activities)
-- ============================================================

create table if not exists harim_nexus.members (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone default now(),
  name text not null,
  "position" text,
  department text,
  email text,
  status text,
  joined_at text,
  skills text[],
  auth_id uuid,
  approved boolean default false,
  message text,
  login_id text,
  constraint members_pkey primary key (id),
  constraint members_login_id_key unique (login_id)
);

create table if not exists harim_nexus.projects (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone default now() not null,
  title text,
  author text,
  period text,
  problem text,
  direction text,
  goal text,
  constraint projects_pkey primary key (id)
);

create table if not exists harim_nexus.tasks (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone default now() not null,
  title text,
  status text,
  priority text,
  assignee text,
  due_date text,
  content text,
  related_doc_id bigint,
  start_date date default current_date,
  progress integer default 0,
  parent_id bigint,
  project_id bigint,
  is_key_task boolean default false,
  acceptance_criteria text,
  deliverable_url text,
  delay_reason text,
  predecessor_id bigint,
  wbs_order numeric default 0,
  constraint tasks_pkey primary key (id)
);

create table if not exists harim_nexus.posts (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone default now() not null,
  title text,
  tag text,
  content text,
  author_name text,
  views bigint,
  comment_count bigint,
  constraint posts_pkey primary key (id)
);

create table if not exists harim_nexus.comments (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone default now() not null,
  post_id bigint,
  content text,
  author_name text,
  constraint comments_pkey primary key (id)
);

create table if not exists harim_nexus.archives (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone default now() not null,
  category text,
  title text,
  link text,
  content text,
  author text,
  constraint archives_pkey primary key (id)
);

create table if not exists harim_nexus.schedules (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone default now(),
  type text,
  sub_type text,
  content text,
  date text,
  "time" text,
  target text,
  constraint schedules_pkey primary key (id)
);

create table if not exists harim_nexus.quick_links (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone default now(),
  name text,
  url text,
  constraint quick_links_pkey primary key (id)
);

create table if not exists harim_nexus.activities (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone default now(),
  user_name text,
  action text,
  constraint activities_pkey primary key (id)
);


-- ============================================================
-- 2. 외래키 · 인덱스
-- ============================================================

-- ============================================================
-- 03. 외래키 · 인덱스 (데이터 적재 후 실행)
-- ============================================================

alter table harim_nexus.members
  add constraint members_auth_id_fkey foreign key (auth_id)
  references auth.users(id) on delete set null;

alter table harim_nexus.tasks
  add constraint tasks_parent_id_fkey foreign key (parent_id)
  references harim_nexus.tasks(id);

alter table harim_nexus.tasks
  add constraint tasks_predecessor_id_fkey foreign key (predecessor_id)
  references harim_nexus.tasks(id) on delete set null;

alter table harim_nexus.tasks
  add constraint tasks_project_id_fkey foreign key (project_id)
  references harim_nexus.projects(id);

create index if not exists idx_tasks_parent_id on harim_nexus.tasks using btree (parent_id);
create index if not exists idx_tasks_predecessor_id on harim_nexus.tasks using btree (predecessor_id);
create index if not exists idx_tasks_project_wbs_order on harim_nexus.tasks using btree (project_id, parent_id, wbs_order);


-- ============================================================
-- 3. 관리자 역할 · 내부 함수 스키마 · members/activities 권한
-- ============================================================

alter table harim_nexus.members
  add column if not exists role text not null default 'member';


alter table harim_nexus.members
  drop constraint if exists members_role_check;

alter table harim_nexus.members
  add constraint members_role_check check (role in ('admin', 'member'));

create unique index if not exists members_auth_id_unique
  on harim_nexus.members (auth_id)
  where auth_id is not null;

create schema if not exists harim_nexus_private;
revoke all on schema harim_nexus_private from public, anon;
grant usage on schema harim_nexus_private to authenticated;

create or replace function harim_nexus_private.is_nexus_admin()
returns boolean
language sql
stable
security definer
set search_path = ''
as $$
  select (select auth.uid()) is not null and exists (
    select 1
    from harim_nexus.members
    where auth_id = (select auth.uid())
      and role = 'admin'
      and approved = true
      and status <> 'pending'
  );
$$;

revoke all on function harim_nexus_private.is_nexus_admin() from public, anon;
grant execute on function harim_nexus_private.is_nexus_admin() to authenticated;

create or replace function harim_nexus_private.is_nexus_member()
returns boolean
language sql
stable
security definer
set search_path = ''
as $$
  select (select auth.uid()) is not null and exists (
    select 1
    from harim_nexus.members
    where auth_id = (select auth.uid())
      and approved = true
      and status <> 'pending'
  );
$$;

revoke all on function harim_nexus_private.is_nexus_member() from public, anon;
grant execute on function harim_nexus_private.is_nexus_member() to authenticated;


alter table harim_nexus.members enable row level security;

drop policy if exists "members_read_self_or_admin" on harim_nexus.members;
create policy "members_read_self_or_admin"
on harim_nexus.members for select
to authenticated
using ((select harim_nexus_private.is_nexus_member()));

drop policy if exists "members_update_own_presence" on harim_nexus.members;
create policy "members_update_own_presence"
on harim_nexus.members for update
to authenticated
using ((select auth.uid()) = auth_id)
with check ((select auth.uid()) = auth_id);

revoke all on table harim_nexus.members from anon;
revoke insert, delete, truncate, references, trigger on table harim_nexus.members from authenticated;
revoke update on table harim_nexus.members from authenticated;
grant select on table harim_nexus.members to authenticated;
grant update (status, message) on table harim_nexus.members to authenticated;

alter table harim_nexus.activities enable row level security;

drop policy if exists "activities_read_members" on harim_nexus.activities;
create policy "activities_read_members"
on harim_nexus.activities for select
to authenticated
using (
  (select harim_nexus_private.is_nexus_member())
);

drop policy if exists "activities_insert_members" on harim_nexus.activities;
create policy "activities_insert_members"
on harim_nexus.activities for insert
to authenticated
with check (
  (select harim_nexus_private.is_nexus_member())
);

revoke all on table harim_nexus.activities from anon;
revoke update, delete, truncate, references, trigger on table harim_nexus.activities from authenticated;
grant select, insert on table harim_nexus.activities to authenticated;


-- ============================================================
-- 4. 조직 · MBO · RACI · 근태
-- ============================================================

-- Organization, MBO, RACI work ownership, and attendance calendar

create table if not exists harim_nexus.org_units (
  id bigint generated by default as identity primary key,
  name text not null,
  unit_type text not null default 'team' check (unit_type in ('company', 'division', 'department', 'team')),
  parent_id bigint references harim_nexus.org_units(id) on delete set null,
  manager_member_id bigint references harim_nexus.members(id) on delete set null,
  description text not null default '',
  sort_order integer not null default 0,
  active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (parent_id, name)
);

create table if not exists harim_nexus.member_role_profiles (
  id bigint generated by default as identity primary key,
  member_id bigint not null unique references harim_nexus.members(id) on delete cascade,
  org_unit_id bigint references harim_nexus.org_units(id) on delete set null,
  job_title text not null default '',
  role_summary text not null default '',
  responsibilities text[] not null default '{}',
  authority_scope text not null default '',
  updated_at timestamptz not null default now()
);

create table if not exists harim_nexus.mbo_objectives (
  id bigint generated by default as identity primary key,
  member_id bigint not null references harim_nexus.members(id) on delete cascade,
  org_unit_id bigint references harim_nexus.org_units(id) on delete set null,
  year integer not null check (year between 2020 and 2100),
  title text not null,
  description text not null default '',
  metric text not null default '',
  target_value text not null default '',
  current_value text not null default '',
  weight numeric(5,2) not null default 0 check (weight between 0 and 100),
  progress integer not null default 0 check (progress between 0 and 100),
  status text not null default 'planned' check (status in ('planned', 'in_progress', 'at_risk', 'completed', 'hold')),
  due_date date,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists harim_nexus.work_responsibilities (
  id bigint generated by default as identity primary key,
  org_unit_id bigint references harim_nexus.org_units(id) on delete set null,
  title text not null,
  description text not null default '',
  output_definition text not null default '',
  cycle text not null default '',
  active boolean not null default true,
  sort_order integer not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists harim_nexus.responsibility_assignments (
  id bigint generated by default as identity primary key,
  responsibility_id bigint not null references harim_nexus.work_responsibilities(id) on delete cascade,
  member_id bigint not null references harim_nexus.members(id) on delete cascade,
  assignment_type text not null check (assignment_type in ('R', 'A', 'C', 'I')),
  created_at timestamptz not null default now(),
  unique (responsibility_id, member_id, assignment_type)
);

create table if not exists harim_nexus.attendance_events (
  id bigint generated by default as identity primary key,
  member_id bigint not null references harim_nexus.members(id) on delete cascade,
  event_type text not null check (event_type in ('annual_leave', 'am_half', 'pm_half', 'quarter_day', 'vacation', 'business_trip', 'outside_work', 'holiday_work')),
  start_date date not null,
  end_date date not null,
  start_time time,
  end_time time,
  unit_days numeric(4,2) not null default 1 check (unit_days > 0 and unit_days <= 31),
  note text not null default '',
  status text not null default 'confirmed' check (status in ('requested', 'confirmed', 'cancelled')),
  created_by uuid default auth.uid() references auth.users(id) on delete set null,
  source_schedule_id bigint unique references harim_nexus.schedules(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  check (end_date >= start_date)
);

create index if not exists idx_org_units_parent on harim_nexus.org_units(parent_id, sort_order);
create unique index if not exists org_units_parent_name_unique
  on harim_nexus.org_units (coalesce(parent_id, 0), lower(name));
create index if not exists idx_role_profiles_org on harim_nexus.member_role_profiles(org_unit_id);
create index if not exists idx_mbo_member_year on harim_nexus.mbo_objectives(member_id, year);
create index if not exists idx_responsibilities_org on harim_nexus.work_responsibilities(org_unit_id, sort_order);
create index if not exists idx_assignments_responsibility on harim_nexus.responsibility_assignments(responsibility_id);
create index if not exists idx_attendance_dates on harim_nexus.attendance_events(start_date, end_date);
create index if not exists idx_attendance_member_dates on harim_nexus.attendance_events(member_id, start_date, end_date);


alter table harim_nexus.org_units enable row level security;
alter table harim_nexus.member_role_profiles enable row level security;
alter table harim_nexus.mbo_objectives enable row level security;
alter table harim_nexus.work_responsibilities enable row level security;
alter table harim_nexus.responsibility_assignments enable row level security;
alter table harim_nexus.attendance_events enable row level security;

do $$
declare table_name text;
begin
  foreach table_name in array array[
    'org_units', 'member_role_profiles', 'mbo_objectives',
    'work_responsibilities', 'responsibility_assignments'
  ] loop
    execute format('drop policy if exists %I on harim_nexus.%I', table_name || '_read_members', table_name);
    execute format(
      'create policy %I on harim_nexus.%I for select to authenticated using ((select harim_nexus_private.is_nexus_member()))',
      table_name || '_read_members', table_name
    );
    execute format('drop policy if exists %I on harim_nexus.%I', table_name || '_admin_all', table_name);
    execute format(
      'create policy %I on harim_nexus.%I for all to authenticated using ((select harim_nexus_private.is_nexus_admin())) with check ((select harim_nexus_private.is_nexus_admin()))',
      table_name || '_admin_all', table_name
    );
  end loop;
end $$;

drop policy if exists attendance_read_members on harim_nexus.attendance_events;
create policy attendance_read_members on harim_nexus.attendance_events
for select to authenticated
using ((select harim_nexus_private.is_nexus_member()));

drop policy if exists attendance_insert_self_or_admin on harim_nexus.attendance_events;
create policy attendance_insert_self_or_admin on harim_nexus.attendance_events
for insert to authenticated
with check (
  (select harim_nexus_private.is_nexus_admin())
  or exists (
    select 1 from harim_nexus.members m
    where m.id = member_id and m.auth_id = (select auth.uid())
  )
);

drop policy if exists attendance_update_self_or_admin on harim_nexus.attendance_events;
create policy attendance_update_self_or_admin on harim_nexus.attendance_events
for update to authenticated
using (
  (select harim_nexus_private.is_nexus_admin())
  or exists (
    select 1 from harim_nexus.members m
    where m.id = member_id and m.auth_id = (select auth.uid())
  )
)
with check (
  (select harim_nexus_private.is_nexus_admin())
  or exists (
    select 1 from harim_nexus.members m
    where m.id = member_id and m.auth_id = (select auth.uid())
  )
);

drop policy if exists attendance_delete_self_or_admin on harim_nexus.attendance_events;
create policy attendance_delete_self_or_admin on harim_nexus.attendance_events
for delete to authenticated
using (
  (select harim_nexus_private.is_nexus_admin())
  or exists (
    select 1 from harim_nexus.members m
    where m.id = member_id and m.auth_id = (select auth.uid())
  )
);

revoke all on harim_nexus.org_units, harim_nexus.member_role_profiles, harim_nexus.mbo_objectives,
  harim_nexus.work_responsibilities, harim_nexus.responsibility_assignments, harim_nexus.attendance_events from anon;
grant select, insert, update, delete on harim_nexus.org_units, harim_nexus.member_role_profiles,
  harim_nexus.mbo_objectives, harim_nexus.work_responsibilities, harim_nexus.responsibility_assignments,
  harim_nexus.attendance_events to authenticated;
grant usage, select on sequence harim_nexus.org_units_id_seq,
  harim_nexus.member_role_profiles_id_seq, harim_nexus.mbo_objectives_id_seq,
  harim_nexus.work_responsibilities_id_seq, harim_nexus.responsibility_assignments_id_seq,
  harim_nexus.attendance_events_id_seq to authenticated;


-- ============================================================
-- 5. 조직 권한 정리
-- ============================================================

-- Keep one SELECT policy per table and split administrator writes by command.
do $$
declare table_name text;
begin
  foreach table_name in array array[
    'org_units', 'member_role_profiles', 'mbo_objectives',
    'work_responsibilities', 'responsibility_assignments'
  ] loop
    execute format('drop policy if exists %I on harim_nexus.%I', table_name || '_admin_all', table_name);

    execute format('drop policy if exists %I on harim_nexus.%I', table_name || '_admin_insert', table_name);
    execute format(
      'create policy %I on harim_nexus.%I for insert to authenticated with check ((select harim_nexus_private.is_nexus_admin()))',
      table_name || '_admin_insert', table_name
    );

    execute format('drop policy if exists %I on harim_nexus.%I', table_name || '_admin_update', table_name);
    execute format(
      'create policy %I on harim_nexus.%I for update to authenticated using ((select harim_nexus_private.is_nexus_admin())) with check ((select harim_nexus_private.is_nexus_admin()))',
      table_name || '_admin_update', table_name
    );

    execute format('drop policy if exists %I on harim_nexus.%I', table_name || '_admin_delete', table_name);
    execute format(
      'create policy %I on harim_nexus.%I for delete to authenticated using ((select harim_nexus_private.is_nexus_admin()))',
      table_name || '_admin_delete', table_name
    );
  end loop;
end $$;


-- ============================================================
-- 6. 조직 FK 인덱스
-- ============================================================

create index if not exists idx_org_units_manager_member
  on harim_nexus.org_units(manager_member_id);

create index if not exists idx_mbo_org_unit
  on harim_nexus.mbo_objectives(org_unit_id);

create index if not exists idx_assignments_member
  on harim_nexus.responsibility_assignments(member_id);

create index if not exists idx_attendance_created_by
  on harim_nexus.attendance_events(created_by);


-- ============================================================
-- 7. Work OS 기반 (워크스페이스·감사·알림·파일·템플릿·목표·자동화·권한)
-- ============================================================

-- Harim Nexus Work OS foundation (P0-P2)
-- P0: workspace isolation, typed comments, soft deletion, auditability and RLS
-- P1: notifications, files, templates, saved views and task relationships
-- P2: goals, automation, webhooks and enterprise workspace settings


create table if not exists harim_nexus.workspaces (
  id uuid primary key default gen_random_uuid(),
  slug text not null unique,
  name text not null,
  description text not null default '',
  default_locale text not null default 'ko-KR',
  timezone text not null default 'Asia/Seoul',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

insert into harim_nexus.workspaces (id, slug, name, description)
values (
  '00000000-0000-4000-8000-000000000001',
  'harim-foods-cost',
  'Harim Foods 원가팀',
  'Harim Nexus 기본 워크스페이스'
)
on conflict (id) do update
set name = excluded.name, description = excluded.description;

create table if not exists harim_nexus.workspace_members (
  workspace_id uuid not null references harim_nexus.workspaces(id) on delete cascade,
  member_id bigint not null references harim_nexus.members(id) on delete cascade,
  role text not null default 'member' check (role in ('owner', 'admin', 'member', 'guest')),
  active boolean not null default true,
  joined_at timestamptz not null default now(),
  primary key (workspace_id, member_id)
);

insert into harim_nexus.workspace_members (workspace_id, member_id, role)
select
  '00000000-0000-4000-8000-000000000001',
  m.id,
  case when m.role = 'admin' then 'owner' else 'member' end
from harim_nexus.members m
where m.approved is true
on conflict (workspace_id, member_id) do update
set role = excluded.role, active = true;

create or replace function harim_nexus_private.current_nexus_member_id()
returns bigint
language sql
stable
security definer
set search_path = ''
as $$
  select m.id
  from harim_nexus.members m
  where m.auth_id = (select auth.uid())
    and m.approved is true
    and m.status <> 'pending'
  limit 1;
$$;

create or replace function harim_nexus_private.has_workspace_access(
  target_workspace uuid,
  allowed_roles text[] default null
)
returns boolean
language sql
stable
security definer
set search_path = ''
as $$
  select (select auth.uid()) is not null and exists (
    select 1
    from harim_nexus.workspace_members wm
    join harim_nexus.members m on m.id = wm.member_id
    where wm.workspace_id = target_workspace
      and wm.active is true
      and m.auth_id = (select auth.uid())
      and m.approved is true
      and m.status <> 'pending'
      and (allowed_roles is null or wm.role = any(allowed_roles))
  );
$$;

revoke all on function harim_nexus_private.current_nexus_member_id() from public, anon;
revoke all on function harim_nexus_private.has_workspace_access(uuid, text[]) from public, anon;
grant execute on function harim_nexus_private.current_nexus_member_id() to authenticated;
grant execute on function harim_nexus_private.has_workspace_access(uuid, text[]) to authenticated;

-- Add a workspace/security envelope to the existing collaboration records.
alter table harim_nexus.tasks
  add column if not exists workspace_id uuid references harim_nexus.workspaces(id),
  add column if not exists assignee_member_id bigint references harim_nexus.members(id) on delete set null,
  add column if not exists created_by_member_id bigint references harim_nexus.members(id) on delete set null,
  add column if not exists deleted_at timestamptz,
  add column if not exists deleted_by uuid references auth.users(id) on delete set null;

alter table harim_nexus.projects
  add column if not exists workspace_id uuid references harim_nexus.workspaces(id),
  add column if not exists author_member_id bigint references harim_nexus.members(id) on delete set null,
  add column if not exists deleted_at timestamptz,
  add column if not exists deleted_by uuid references auth.users(id) on delete set null;

alter table harim_nexus.posts
  add column if not exists workspace_id uuid references harim_nexus.workspaces(id),
  add column if not exists author_member_id bigint references harim_nexus.members(id) on delete set null,
  add column if not exists deleted_at timestamptz,
  add column if not exists deleted_by uuid references auth.users(id) on delete set null;

alter table harim_nexus.archives
  add column if not exists workspace_id uuid references harim_nexus.workspaces(id),
  add column if not exists author_member_id bigint references harim_nexus.members(id) on delete set null,
  add column if not exists deleted_at timestamptz,
  add column if not exists deleted_by uuid references auth.users(id) on delete set null;

alter table harim_nexus.comments
  add column if not exists workspace_id uuid references harim_nexus.workspaces(id),
  add column if not exists entity_type text,
  add column if not exists entity_id bigint,
  add column if not exists author_member_id bigint references harim_nexus.members(id) on delete set null,
  add column if not exists deleted_at timestamptz,
  add column if not exists deleted_by uuid references auth.users(id) on delete set null;

alter table harim_nexus.schedules
  add column if not exists workspace_id uuid references harim_nexus.workspaces(id),
  add column if not exists created_by_member_id bigint references harim_nexus.members(id) on delete set null,
  add column if not exists deleted_at timestamptz,
  add column if not exists deleted_by uuid references auth.users(id) on delete set null;

alter table harim_nexus.quick_links
  add column if not exists workspace_id uuid references harim_nexus.workspaces(id),
  add column if not exists deleted_at timestamptz,
  add column if not exists deleted_by uuid references auth.users(id) on delete set null;

alter table harim_nexus.activities
  add column if not exists workspace_id uuid references harim_nexus.workspaces(id),
  add column if not exists actor_member_id bigint references harim_nexus.members(id) on delete set null;

update harim_nexus.tasks t
set workspace_id = '00000000-0000-4000-8000-000000000001',
    assignee_member_id = coalesce(t.assignee_member_id, (
      select m.id from harim_nexus.members m where trim(m.name) = trim(t.assignee) limit 1
    ))
where t.workspace_id is null or t.assignee_member_id is null;

update harim_nexus.projects p
set workspace_id = '00000000-0000-4000-8000-000000000001',
    author_member_id = coalesce(p.author_member_id, (
      select m.id from harim_nexus.members m where trim(m.name) = trim(p.author) limit 1
    ))
where p.workspace_id is null or p.author_member_id is null;

update harim_nexus.posts p
set workspace_id = '00000000-0000-4000-8000-000000000001',
    author_member_id = coalesce(p.author_member_id, (
      select m.id from harim_nexus.members m where trim(m.name) = trim(p.author_name) limit 1
    ))
where p.workspace_id is null or p.author_member_id is null;

update harim_nexus.archives a
set workspace_id = '00000000-0000-4000-8000-000000000001',
    author_member_id = coalesce(a.author_member_id, (
      select m.id from harim_nexus.members m where trim(m.name) = trim(a.author) limit 1
    ))
where a.workspace_id is null or a.author_member_id is null;

-- Existing comments were verified against production: all eight belong to tasks.
update harim_nexus.comments c
set workspace_id = '00000000-0000-4000-8000-000000000001',
    entity_type = coalesce(c.entity_type, 'task'),
    entity_id = coalesce(c.entity_id, c.post_id),
    author_member_id = coalesce(c.author_member_id, (
      select m.id from harim_nexus.members m where trim(m.name) = trim(c.author_name) limit 1
    ))
where c.workspace_id is null or c.entity_type is null or c.entity_id is null or c.author_member_id is null;

update harim_nexus.schedules s
set workspace_id = '00000000-0000-4000-8000-000000000001',
    created_by_member_id = coalesce(s.created_by_member_id, (
      select m.id from harim_nexus.members m where trim(m.name) = trim(s.target) limit 1
    ))
where s.workspace_id is null or s.created_by_member_id is null;

update harim_nexus.quick_links set workspace_id = '00000000-0000-4000-8000-000000000001' where workspace_id is null;
update harim_nexus.activities a
set workspace_id = '00000000-0000-4000-8000-000000000001',
    actor_member_id = coalesce(a.actor_member_id, (
      select m.id from harim_nexus.members m where trim(m.name) = trim(a.user_name) limit 1
    ))
where a.workspace_id is null or a.actor_member_id is null;

alter table harim_nexus.tasks alter column workspace_id set default '00000000-0000-4000-8000-000000000001';
alter table harim_nexus.projects alter column workspace_id set default '00000000-0000-4000-8000-000000000001';
alter table harim_nexus.posts alter column workspace_id set default '00000000-0000-4000-8000-000000000001';
alter table harim_nexus.archives alter column workspace_id set default '00000000-0000-4000-8000-000000000001';
alter table harim_nexus.comments alter column workspace_id set default '00000000-0000-4000-8000-000000000001';
alter table harim_nexus.schedules alter column workspace_id set default '00000000-0000-4000-8000-000000000001';
alter table harim_nexus.quick_links alter column workspace_id set default '00000000-0000-4000-8000-000000000001';
alter table harim_nexus.activities alter column workspace_id set default '00000000-0000-4000-8000-000000000001';

alter table harim_nexus.tasks alter column workspace_id set not null;
alter table harim_nexus.projects alter column workspace_id set not null;
alter table harim_nexus.posts alter column workspace_id set not null;
alter table harim_nexus.archives alter column workspace_id set not null;
alter table harim_nexus.comments alter column workspace_id set not null;
alter table harim_nexus.comments alter column entity_type set not null;
alter table harim_nexus.comments alter column entity_id set not null;
alter table harim_nexus.schedules alter column workspace_id set not null;
alter table harim_nexus.quick_links alter column workspace_id set not null;
alter table harim_nexus.activities alter column workspace_id set not null;

alter table harim_nexus.comments drop constraint if exists comments_entity_type_check;
alter table harim_nexus.comments add constraint comments_entity_type_check
  check (entity_type in ('task', 'post', 'archive', 'project'));

create index if not exists idx_tasks_workspace_due on harim_nexus.tasks(workspace_id, due_date) where deleted_at is null;
create index if not exists idx_tasks_assignee_status on harim_nexus.tasks(assignee_member_id, status) where deleted_at is null;
create index if not exists idx_projects_workspace on harim_nexus.projects(workspace_id) where deleted_at is null;
create index if not exists idx_posts_workspace_created on harim_nexus.posts(workspace_id, created_at desc) where deleted_at is null;
create index if not exists idx_archives_workspace_created on harim_nexus.archives(workspace_id, created_at desc) where deleted_at is null;
create index if not exists idx_comments_entity on harim_nexus.comments(workspace_id, entity_type, entity_id, created_at) where deleted_at is null;
create index if not exists idx_schedules_workspace_date on harim_nexus.schedules(workspace_id, date) where deleted_at is null;

create table if not exists harim_nexus.audit_events (
  id bigint generated by default as identity primary key,
  workspace_id uuid not null references harim_nexus.workspaces(id) on delete cascade,
  actor_id uuid references auth.users(id) on delete set null,
  actor_member_id bigint references harim_nexus.members(id) on delete set null,
  entity_type text not null,
  entity_id text not null,
  action text not null check (action in ('create', 'update', 'soft_delete', 'restore', 'delete', 'automation')),
  changed_fields text[] not null default '{}',
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create index if not exists idx_audit_workspace_created on harim_nexus.audit_events(workspace_id, created_at desc);
create index if not exists idx_audit_entity on harim_nexus.audit_events(entity_type, entity_id, created_at desc);

create or replace function harim_nexus_private.audit_nexus_change()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
declare
  row_json jsonb;
  old_json jsonb;
  action_name text;
  changed text[];
begin
  row_json := case when tg_op = 'DELETE' then to_jsonb(old) else to_jsonb(new) end;
  old_json := case when tg_op = 'UPDATE' then to_jsonb(old) else '{}'::jsonb end;

  if tg_op = 'INSERT' then
    action_name := 'create';
  elsif tg_op = 'DELETE' then
    action_name := 'delete';
  elsif (old_json->>'deleted_at') is null and (row_json->>'deleted_at') is not null then
    action_name := 'soft_delete';
  elsif (old_json->>'deleted_at') is not null and (row_json->>'deleted_at') is null then
    action_name := 'restore';
  else
    action_name := 'update';
  end if;

  if tg_op = 'UPDATE' then
    select coalesce(array_agg(key order by key), '{}') into changed
    from jsonb_each(row_json) n(key, value)
    where old_json->n.key is distinct from n.value
      and n.key not in ('updated_at');
  else
    changed := '{}';
  end if;

  insert into harim_nexus.audit_events (
    workspace_id, actor_id, actor_member_id, entity_type, entity_id, action, changed_fields
  ) values (
    (row_json->>'workspace_id')::uuid,
    (select auth.uid()),
    (select harim_nexus_private.current_nexus_member_id()),
    tg_table_name,
    row_json->>'id',
    action_name,
    changed
  );

  return case when tg_op = 'DELETE' then old else new end;
end;
$$;

revoke all on function harim_nexus_private.audit_nexus_change() from public, anon, authenticated;

do $$
declare table_name text;
begin
  foreach table_name in array array['tasks', 'projects', 'posts', 'archives', 'comments', 'schedules', 'quick_links'] loop
    execute format('drop trigger if exists audit_nexus_change on harim_nexus.%I', table_name);
    execute format(
      'create trigger audit_nexus_change after insert or update or delete on harim_nexus.%I for each row execute function harim_nexus_private.audit_nexus_change()',
      table_name
    );
  end loop;
end $$;

-- P1 daily collaboration loop.
create table if not exists harim_nexus.notifications (
  id bigint generated by default as identity primary key,
  workspace_id uuid not null references harim_nexus.workspaces(id) on delete cascade,
  recipient_member_id bigint not null references harim_nexus.members(id) on delete cascade,
  actor_member_id bigint references harim_nexus.members(id) on delete set null,
  kind text not null check (kind in ('assignment', 'mention', 'comment', 'due', 'status', 'system', 'automation')),
  title text not null,
  body text not null default '',
  entity_type text,
  entity_id text,
  action_url text,
  read_at timestamptz,
  created_at timestamptz not null default now()
);

create table if not exists harim_nexus.task_relations (
  id bigint generated by default as identity primary key,
  workspace_id uuid not null references harim_nexus.workspaces(id) on delete cascade,
  source_task_id bigint not null references harim_nexus.tasks(id) on delete cascade,
  target_task_id bigint not null references harim_nexus.tasks(id) on delete cascade,
  relation_type text not null check (relation_type in ('blocks', 'related', 'duplicate')),
  created_by_member_id bigint references harim_nexus.members(id) on delete set null,
  created_at timestamptz not null default now(),
  unique (source_task_id, target_task_id, relation_type),
  check (source_task_id <> target_task_id)
);

create table if not exists harim_nexus.workspace_files (
  id uuid primary key default gen_random_uuid(),
  workspace_id uuid not null references harim_nexus.workspaces(id) on delete cascade,
  entity_type text,
  entity_id text,
  storage_path text not null unique,
  file_name text not null,
  mime_type text,
  size_bytes bigint not null default 0 check (size_bytes >= 0),
  version integer not null default 1 check (version > 0),
  uploaded_by_member_id bigint references harim_nexus.members(id) on delete set null,
  deleted_at timestamptz,
  created_at timestamptz not null default now()
);

create table if not exists harim_nexus.task_templates (
  id bigint generated by default as identity primary key,
  workspace_id uuid not null references harim_nexus.workspaces(id) on delete cascade,
  name text not null,
  description text not null default '',
  default_priority text not null default '보통',
  default_status text not null default '대기',
  content text not null default '',
  checklist jsonb not null default '[]'::jsonb,
  recurrence_rule text,
  created_by_member_id bigint references harim_nexus.members(id) on delete set null,
  active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (workspace_id, name)
);

create table if not exists harim_nexus.saved_views (
  id bigint generated by default as identity primary key,
  workspace_id uuid not null references harim_nexus.workspaces(id) on delete cascade,
  member_id bigint not null references harim_nexus.members(id) on delete cascade,
  name text not null,
  surface text not null,
  filters jsonb not null default '{}'::jsonb,
  is_default boolean not null default false,
  created_at timestamptz not null default now(),
  unique (workspace_id, member_id, surface, name)
);

create table if not exists harim_nexus.notification_preferences (
  workspace_id uuid not null references harim_nexus.workspaces(id) on delete cascade,
  member_id bigint not null references harim_nexus.members(id) on delete cascade,
  in_app boolean not null default true,
  email boolean not null default false,
  mentions boolean not null default true,
  assignments boolean not null default true,
  due_reminders boolean not null default true,
  updated_at timestamptz not null default now(),
  primary key (workspace_id, member_id)
);

create index if not exists idx_notifications_member_unread on harim_nexus.notifications(recipient_member_id, created_at desc) where read_at is null;
create index if not exists idx_task_relations_source on harim_nexus.task_relations(source_task_id);
create index if not exists idx_task_relations_target on harim_nexus.task_relations(target_task_id);
create index if not exists idx_workspace_files_entity on harim_nexus.workspace_files(workspace_id, entity_type, entity_id) where deleted_at is null;

insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values (
  'nexus-files', 'nexus-files', false, 52428800,
  array['application/pdf','image/png','image/jpeg','image/webp','text/plain','text/csv','application/vnd.openxmlformats-officedocument.spreadsheetml.sheet','application/vnd.openxmlformats-officedocument.wordprocessingml.document']
)
on conflict (id) do update
set public = false, file_size_limit = excluded.file_size_limit, allowed_mime_types = excluded.allowed_mime_types;

-- P2 automation, integrations, portfolio and enterprise controls.
create table if not exists harim_nexus.goals (
  id bigint generated by default as identity primary key,
  workspace_id uuid not null references harim_nexus.workspaces(id) on delete cascade,
  parent_goal_id bigint references harim_nexus.goals(id) on delete set null,
  owner_member_id bigint references harim_nexus.members(id) on delete set null,
  title text not null,
  description text not null default '',
  status text not null default 'on_track' check (status in ('on_track', 'at_risk', 'off_track', 'completed', 'paused')),
  progress integer not null default 0 check (progress between 0 and 100),
  start_date date,
  due_date date,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists harim_nexus.goal_links (
  goal_id bigint not null references harim_nexus.goals(id) on delete cascade,
  entity_type text not null check (entity_type in ('project', 'task', 'mbo')),
  entity_id text not null,
  weight numeric(5,2) not null default 0 check (weight between 0 and 100),
  primary key (goal_id, entity_type, entity_id)
);

create table if not exists harim_nexus.automation_rules (
  id bigint generated by default as identity primary key,
  workspace_id uuid not null references harim_nexus.workspaces(id) on delete cascade,
  name text not null,
  trigger_type text not null check (trigger_type in ('manual', 'task_created', 'task_status_changed', 'task_due')),
  conditions jsonb not null default '{}'::jsonb,
  action_type text not null check (action_type in ('notify', 'update_task', 'webhook')),
  action_config jsonb not null default '{}'::jsonb,
  enabled boolean not null default true,
  created_by_member_id bigint references harim_nexus.members(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists harim_nexus.automation_runs (
  id bigint generated by default as identity primary key,
  workspace_id uuid not null references harim_nexus.workspaces(id) on delete cascade,
  rule_id bigint not null references harim_nexus.automation_rules(id) on delete cascade,
  status text not null check (status in ('running', 'success', 'failed', 'skipped')),
  trigger_payload jsonb not null default '{}'::jsonb,
  result jsonb not null default '{}'::jsonb,
  error_message text,
  started_at timestamptz not null default now(),
  finished_at timestamptz
);

create table if not exists harim_nexus.webhook_endpoints (
  id uuid primary key default gen_random_uuid(),
  workspace_id uuid not null references harim_nexus.workspaces(id) on delete cascade,
  name text not null,
  endpoint_url text not null,
  event_types text[] not null default '{}',
  enabled boolean not null default true,
  created_by_member_id bigint references harim_nexus.members(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  check (endpoint_url ~ '^https://')
);

create table if not exists harim_nexus.webhook_deliveries (
  id bigint generated by default as identity primary key,
  workspace_id uuid not null references harim_nexus.workspaces(id) on delete cascade,
  endpoint_id uuid not null references harim_nexus.webhook_endpoints(id) on delete cascade,
  event_type text not null,
  payload jsonb not null default '{}'::jsonb,
  status text not null default 'pending' check (status in ('pending', 'success', 'failed')),
  response_status integer,
  error_message text,
  attempted_at timestamptz,
  created_at timestamptz not null default now()
);

create table if not exists harim_nexus.workspace_settings (
  workspace_id uuid primary key references harim_nexus.workspaces(id) on delete cascade,
  require_mfa boolean not null default false,
  allowed_email_domains text[] not null default '{}',
  session_timeout_minutes integer not null default 480 check (session_timeout_minutes between 15 and 43200),
  data_retention_days integer not null default 3650 check (data_retention_days between 30 and 36500),
  audit_retention_days integer not null default 3650 check (audit_retention_days between 90 and 36500),
  updated_by_member_id bigint references harim_nexus.members(id) on delete set null,
  updated_at timestamptz not null default now()
);

insert into harim_nexus.workspace_settings (workspace_id)
values ('00000000-0000-4000-8000-000000000001')
on conflict (workspace_id) do nothing;

create index if not exists idx_goals_workspace_status on harim_nexus.goals(workspace_id, status, due_date);
create index if not exists idx_automation_rules_trigger on harim_nexus.automation_rules(workspace_id, trigger_type) where enabled is true;
create index if not exists idx_automation_runs_rule_started on harim_nexus.automation_runs(rule_id, started_at desc);
create index if not exists idx_webhook_deliveries_pending on harim_nexus.webhook_deliveries(status, created_at) where status = 'pending';

-- Workspace-aware RLS for every Harim Nexus table exposed to PostgREST.
alter table harim_nexus.workspaces enable row level security;
alter table harim_nexus.workspace_members enable row level security;
alter table harim_nexus.tasks enable row level security;
alter table harim_nexus.projects enable row level security;
alter table harim_nexus.posts enable row level security;
alter table harim_nexus.archives enable row level security;
alter table harim_nexus.comments enable row level security;
alter table harim_nexus.schedules enable row level security;
alter table harim_nexus.quick_links enable row level security;
alter table harim_nexus.audit_events enable row level security;
alter table harim_nexus.notifications enable row level security;
alter table harim_nexus.task_relations enable row level security;
alter table harim_nexus.workspace_files enable row level security;
alter table harim_nexus.task_templates enable row level security;
alter table harim_nexus.saved_views enable row level security;
alter table harim_nexus.notification_preferences enable row level security;
alter table harim_nexus.goals enable row level security;
alter table harim_nexus.goal_links enable row level security;
alter table harim_nexus.automation_rules enable row level security;
alter table harim_nexus.automation_runs enable row level security;
alter table harim_nexus.webhook_endpoints enable row level security;
alter table harim_nexus.webhook_deliveries enable row level security;
alter table harim_nexus.workspace_settings enable row level security;

drop policy if exists workspaces_read_members on harim_nexus.workspaces;
create policy workspaces_read_members on harim_nexus.workspaces for select to authenticated
using ((select harim_nexus_private.has_workspace_access(id, null)));

drop policy if exists workspaces_admin_update on harim_nexus.workspaces;
create policy workspaces_admin_update on harim_nexus.workspaces for update to authenticated
using ((select harim_nexus_private.has_workspace_access(id, array['owner','admin'])))
with check ((select harim_nexus_private.has_workspace_access(id, array['owner','admin'])));

drop policy if exists workspace_members_read on harim_nexus.workspace_members;
create policy workspace_members_read on harim_nexus.workspace_members for select to authenticated
using ((select harim_nexus_private.has_workspace_access(workspace_id, null)));

drop policy if exists workspace_members_admin_insert on harim_nexus.workspace_members;
create policy workspace_members_admin_insert on harim_nexus.workspace_members for insert to authenticated
with check ((select harim_nexus_private.has_workspace_access(workspace_id, array['owner','admin'])));

drop policy if exists workspace_members_admin_update on harim_nexus.workspace_members;
create policy workspace_members_admin_update on harim_nexus.workspace_members for update to authenticated
using ((select harim_nexus_private.has_workspace_access(workspace_id, array['owner','admin'])))
with check ((select harim_nexus_private.has_workspace_access(workspace_id, array['owner','admin'])));

drop policy if exists workspace_members_admin_delete on harim_nexus.workspace_members;
create policy workspace_members_admin_delete on harim_nexus.workspace_members for delete to authenticated
using ((select harim_nexus_private.has_workspace_access(workspace_id, array['owner','admin'])));

do $$
declare table_name text;
begin
  foreach table_name in array array['tasks', 'projects', 'posts', 'archives', 'comments', 'schedules'] loop
    execute format('drop policy if exists %I on harim_nexus.%I', table_name || '_workspace_read', table_name);
    execute format(
      'create policy %I on harim_nexus.%I for select to authenticated using ((select harim_nexus_private.has_workspace_access(workspace_id, null)) and (deleted_at is null or (select harim_nexus_private.has_workspace_access(workspace_id, array[''owner'',''admin'']))))',
      table_name || '_workspace_read', table_name
    );
    execute format('drop policy if exists %I on harim_nexus.%I', table_name || '_workspace_insert', table_name);
    execute format(
      'create policy %I on harim_nexus.%I for insert to authenticated with check ((select harim_nexus_private.has_workspace_access(workspace_id, array[''owner'',''admin'',''member''])))',
      table_name || '_workspace_insert', table_name
    );
    execute format('drop policy if exists %I on harim_nexus.%I', table_name || '_workspace_update', table_name);
    execute format(
      'create policy %I on harim_nexus.%I for update to authenticated using ((select harim_nexus_private.has_workspace_access(workspace_id, array[''owner'',''admin'',''member'']))) with check ((select harim_nexus_private.has_workspace_access(workspace_id, array[''owner'',''admin'',''member''])))',
      table_name || '_workspace_update', table_name
    );
    execute format('drop policy if exists %I on harim_nexus.%I', table_name || '_workspace_delete', table_name);
    execute format(
      'create policy %I on harim_nexus.%I for delete to authenticated using ((select harim_nexus_private.has_workspace_access(workspace_id, array[''owner'',''admin''])))',
      table_name || '_workspace_delete', table_name
    );
  end loop;
end $$;

drop policy if exists quick_links_workspace_read on harim_nexus.quick_links;
create policy quick_links_workspace_read on harim_nexus.quick_links for select to authenticated
using ((select harim_nexus_private.has_workspace_access(workspace_id, null)) and (deleted_at is null or (select harim_nexus_private.has_workspace_access(workspace_id, array['owner','admin']))));
drop policy if exists quick_links_workspace_admin_insert on harim_nexus.quick_links;
create policy quick_links_workspace_admin_insert on harim_nexus.quick_links for insert to authenticated
with check ((select harim_nexus_private.has_workspace_access(workspace_id, array['owner','admin'])));
drop policy if exists quick_links_workspace_admin_update on harim_nexus.quick_links;
create policy quick_links_workspace_admin_update on harim_nexus.quick_links for update to authenticated
using ((select harim_nexus_private.has_workspace_access(workspace_id, array['owner','admin'])))
with check ((select harim_nexus_private.has_workspace_access(workspace_id, array['owner','admin'])));
drop policy if exists quick_links_workspace_admin_delete on harim_nexus.quick_links;
create policy quick_links_workspace_admin_delete on harim_nexus.quick_links for delete to authenticated
using ((select harim_nexus_private.has_workspace_access(workspace_id, array['owner','admin'])));

drop policy if exists activities_read_members on harim_nexus.activities;
create policy activities_read_members on harim_nexus.activities for select to authenticated
using ((select harim_nexus_private.has_workspace_access(workspace_id, null)));
drop policy if exists activities_insert_members on harim_nexus.activities;
create policy activities_insert_members on harim_nexus.activities for insert to authenticated
with check ((select harim_nexus_private.has_workspace_access(workspace_id, array['owner','admin','member'])));

-- Standard workspace tables: members can read/write collaboration data; admin-only tables are handled below.
do $$
declare table_name text;
begin
  foreach table_name in array array['task_relations', 'workspace_files', 'task_templates', 'saved_views', 'notification_preferences', 'goals'] loop
    execute format('drop policy if exists %I on harim_nexus.%I', table_name || '_workspace_read', table_name);
    execute format(
      'create policy %I on harim_nexus.%I for select to authenticated using ((select harim_nexus_private.has_workspace_access(workspace_id, null)))',
      table_name || '_workspace_read', table_name
    );
    execute format('drop policy if exists %I on harim_nexus.%I', table_name || '_workspace_write', table_name);
    execute format(
      'create policy %I on harim_nexus.%I for all to authenticated using ((select harim_nexus_private.has_workspace_access(workspace_id, array[''owner'',''admin'',''member'']))) with check ((select harim_nexus_private.has_workspace_access(workspace_id, array[''owner'',''admin'',''member''])))',
      table_name || '_workspace_write', table_name
    );
  end loop;
end $$;

-- goal_links derives workspace from goals and therefore needs its own policy.
drop policy if exists goal_links_workspace_read on harim_nexus.goal_links;
drop policy if exists goal_links_workspace_write on harim_nexus.goal_links;
create policy goal_links_read on harim_nexus.goal_links for select to authenticated
using (exists (
  select 1 from harim_nexus.goals g
  where g.id = goal_id and (select harim_nexus_private.has_workspace_access(g.workspace_id, null))
));
create policy goal_links_write on harim_nexus.goal_links for all to authenticated
using (exists (
  select 1 from harim_nexus.goals g
  where g.id = goal_id and (select harim_nexus_private.has_workspace_access(g.workspace_id, array['owner','admin','member']))
))
with check (exists (
  select 1 from harim_nexus.goals g
  where g.id = goal_id and (select harim_nexus_private.has_workspace_access(g.workspace_id, array['owner','admin','member']))
));

drop policy if exists notifications_recipient_read on harim_nexus.notifications;
create policy notifications_recipient_read on harim_nexus.notifications for select to authenticated
using (
  recipient_member_id = (select harim_nexus_private.current_nexus_member_id())
  or (select harim_nexus_private.has_workspace_access(workspace_id, array['owner','admin']))
);
drop policy if exists notifications_member_insert on harim_nexus.notifications;
create policy notifications_member_insert on harim_nexus.notifications for insert to authenticated
with check ((select harim_nexus_private.has_workspace_access(workspace_id, array['owner','admin','member'])));
drop policy if exists notifications_recipient_update on harim_nexus.notifications;
create policy notifications_recipient_update on harim_nexus.notifications for update to authenticated
using (recipient_member_id = (select harim_nexus_private.current_nexus_member_id()))
with check (recipient_member_id = (select harim_nexus_private.current_nexus_member_id()));

drop policy if exists audit_events_admin_read on harim_nexus.audit_events;
create policy audit_events_admin_read on harim_nexus.audit_events for select to authenticated
using ((select harim_nexus_private.has_workspace_access(workspace_id, array['owner','admin'])));

do $$
declare table_name text;
begin
  foreach table_name in array array['automation_rules', 'automation_runs', 'webhook_endpoints', 'webhook_deliveries', 'workspace_settings'] loop
    execute format('drop policy if exists %I on harim_nexus.%I', table_name || '_admin_all', table_name);
    execute format(
      'create policy %I on harim_nexus.%I for all to authenticated using ((select harim_nexus_private.has_workspace_access(workspace_id, array[''owner'',''admin'']))) with check ((select harim_nexus_private.has_workspace_access(workspace_id, array[''owner'',''admin''])))',
      table_name || '_admin_all', table_name
    );
  end loop;
end $$;

-- Private bucket: first path segment must be a workspace UUID the user belongs to.
drop policy if exists nexus_files_select on storage.objects;
create policy nexus_files_select on storage.objects for select to authenticated
using (
  bucket_id = 'nexus-files'
  and (storage.foldername(name))[1] ~ '^[0-9a-f-]{36}$'
  and (select harim_nexus_private.has_workspace_access(((storage.foldername(name))[1])::uuid, null))
);
drop policy if exists nexus_files_insert on storage.objects;
create policy nexus_files_insert on storage.objects for insert to authenticated
with check (
  bucket_id = 'nexus-files'
  and (storage.foldername(name))[1] ~ '^[0-9a-f-]{36}$'
  and (select harim_nexus_private.has_workspace_access(((storage.foldername(name))[1])::uuid, array['owner','admin','member']))
);
drop policy if exists nexus_files_update on storage.objects;
create policy nexus_files_update on storage.objects for update to authenticated
using (
  bucket_id = 'nexus-files'
  and (storage.foldername(name))[1] ~ '^[0-9a-f-]{36}$'
  and (select harim_nexus_private.has_workspace_access(((storage.foldername(name))[1])::uuid, array['owner','admin','member']))
)
with check (
  bucket_id = 'nexus-files'
  and (storage.foldername(name))[1] ~ '^[0-9a-f-]{36}$'
  and (select harim_nexus_private.has_workspace_access(((storage.foldername(name))[1])::uuid, array['owner','admin','member']))
);
drop policy if exists nexus_files_delete on storage.objects;
create policy nexus_files_delete on storage.objects for delete to authenticated
using (
  bucket_id = 'nexus-files'
  and (storage.foldername(name))[1] ~ '^[0-9a-f-]{36}$'
  and (select harim_nexus_private.has_workspace_access(((storage.foldername(name))[1])::uuid, array['owner','admin']))
);

-- Explicit API grants are required for new Supabase projects and future Data API defaults.
revoke all on table harim_nexus.workspaces, harim_nexus.workspace_members, harim_nexus.audit_events,
  harim_nexus.notifications, harim_nexus.task_relations, harim_nexus.workspace_files, harim_nexus.task_templates,
  harim_nexus.saved_views, harim_nexus.notification_preferences, harim_nexus.goals, harim_nexus.goal_links,
  harim_nexus.automation_rules, harim_nexus.automation_runs, harim_nexus.webhook_endpoints,
  harim_nexus.webhook_deliveries, harim_nexus.workspace_settings from anon;

grant select, insert, update, delete on table harim_nexus.workspaces, harim_nexus.workspace_members,
  harim_nexus.notifications, harim_nexus.task_relations, harim_nexus.workspace_files, harim_nexus.task_templates,
  harim_nexus.saved_views, harim_nexus.notification_preferences, harim_nexus.goals, harim_nexus.goal_links,
  harim_nexus.automation_rules, harim_nexus.automation_runs, harim_nexus.webhook_endpoints,
  harim_nexus.webhook_deliveries, harim_nexus.workspace_settings to authenticated;
grant select on table harim_nexus.audit_events to authenticated;

grant select, insert, update, delete on table harim_nexus.tasks, harim_nexus.projects, harim_nexus.posts,
  harim_nexus.archives, harim_nexus.comments, harim_nexus.schedules, harim_nexus.quick_links to authenticated;
revoke all on table harim_nexus.tasks, harim_nexus.projects, harim_nexus.posts, harim_nexus.archives,
  harim_nexus.comments, harim_nexus.schedules, harim_nexus.quick_links from anon;

grant usage, select on sequence
  harim_nexus.audit_events_id_seq,
  harim_nexus.notifications_id_seq,
  harim_nexus.task_relations_id_seq,
  harim_nexus.task_templates_id_seq,
  harim_nexus.saved_views_id_seq,
  harim_nexus.goals_id_seq,
  harim_nexus.automation_rules_id_seq,
  harim_nexus.automation_runs_id_seq,
  harim_nexus.webhook_deliveries_id_seq
to authenticated;


-- ============================================================
-- 8. 조회 RPC (미확인 알림 수, 통합검색)
-- ============================================================

-- Cost-safe, RLS-aware read APIs for the global shell and search surface.

create or replace function harim_nexus.nexus_unread_notification_count()
returns bigint
language sql
stable
security invoker
set search_path = ''
as $$
  select count(*)
  from harim_nexus.notifications n
  where n.recipient_member_id = (select harim_nexus_private.current_nexus_member_id())
    and n.read_at is null;
$$;

revoke all on function harim_nexus.nexus_unread_notification_count() from public, anon;
grant execute on function harim_nexus.nexus_unread_notification_count() to authenticated;

create or replace function harim_nexus.nexus_global_search(
  query_text text,
  per_type_limit integer default 8
)
returns table (
  entity_type text,
  entity_id bigint,
  title text,
  content text,
  metadata jsonb,
  created_at timestamptz
)
language sql
stable
security invoker
set search_path = ''
as $$
  with params as (
    select
      '%' || replace(replace(trim(query_text), '%', ''), '_', '') || '%' as pattern,
      greatest(1, least(coalesce(per_type_limit, 8), 20)) as row_limit,
      length(trim(coalesce(query_text, ''))) >= 2 as valid
  )
  select result.entity_type, result.entity_id, result.title, result.content, result.metadata, result.created_at
  from (
    (
      select 'task'::text as entity_type, t.id as entity_id, coalesce(t.title, '') as title,
        coalesce(t.content, '') as content,
        jsonb_build_object('status', t.status, 'due_date', t.due_date, 'priority', t.priority) as metadata,
        t.created_at as created_at
      from harim_nexus.tasks t, params p
      where p.valid and t.deleted_at is null
        and (t.title ilike p.pattern or t.content ilike p.pattern)
      order by t.created_at desc
      limit (select row_limit from params)
    )
    union all
    (
      select 'project'::text, pjt.id, coalesce(pjt.title, ''),
        concat_ws(E'\n', pjt.problem, pjt.direction, pjt.goal),
        jsonb_build_object('period', pjt.period), pjt.created_at
      from harim_nexus.projects pjt, params p
      where p.valid and pjt.deleted_at is null
        and (pjt.title ilike p.pattern or pjt.problem ilike p.pattern or pjt.direction ilike p.pattern or pjt.goal ilike p.pattern)
      order by pjt.created_at desc
      limit (select row_limit from params)
    )
    union all
    (
      select 'post'::text, p.id, coalesce(p.title, ''), coalesce(p.content, ''),
        jsonb_build_object('tag', p.tag), p.created_at
      from harim_nexus.posts p, params prm
      where prm.valid and p.deleted_at is null
        and (p.title ilike prm.pattern or p.content ilike prm.pattern)
      order by p.created_at desc
      limit (select row_limit from params)
    )
    union all
    (
      select 'archive'::text, a.id, coalesce(a.title, ''), coalesce(a.content, ''),
        jsonb_build_object('category', a.category), a.created_at
      from harim_nexus.archives a, params p
      where p.valid and a.deleted_at is null
        and (a.title ilike p.pattern or a.content ilike p.pattern)
      order by a.created_at desc
      limit (select row_limit from params)
    )
  ) result
  order by result.created_at desc nulls last;
$$;

revoke all on function harim_nexus.nexus_global_search(text, integer) from public, anon;
grant execute on function harim_nexus.nexus_global_search(text, integer) to authenticated;


-- ============================================================
-- 9. 권한 완화 (2026-09-29 결정: 가입은 간단히, 권한은 너무 보수적이지 않게)
--    가입은 /api/auth/signup 이 바로 승인까지 처리한다.
-- ============================================================

-- 퀵링크: 팀원 누구나 추가·수정 (삭제는 휴지통 이동 = update)
drop policy if exists quick_links_workspace_admin_insert on harim_nexus.quick_links;
drop policy if exists quick_links_workspace_admin_update on harim_nexus.quick_links;
drop policy if exists quick_links_workspace_member_insert on harim_nexus.quick_links;
create policy quick_links_workspace_member_insert on harim_nexus.quick_links for insert to authenticated
with check ((select harim_nexus_private.has_workspace_access(workspace_id, array['owner','admin','member'])));
drop policy if exists quick_links_workspace_member_update on harim_nexus.quick_links;
create policy quick_links_workspace_member_update on harim_nexus.quick_links for update to authenticated
using ((select harim_nexus_private.has_workspace_access(workspace_id, array['owner','admin','member'])))
with check ((select harim_nexus_private.has_workspace_access(workspace_id, array['owner','admin','member'])));

-- 휴지통 이동(삭제 표시) 허용: 원래 규칙은 "삭제 표시된 행은 관리자만 읽기"라서
-- 팀원이 삭제 표시를 하면 자기가 못 읽는 행이 되어 DB 가 거부했다. 읽기는 워크스페이스 구성원 전체로 두고
-- 삭제 표시된 행은 화면 조회에서 deleted_at is null 로 걸러낸다. (완전 삭제는 여전히 관리자만)
do $$
declare table_name text;
begin
  foreach table_name in array array['tasks', 'projects', 'posts', 'archives', 'comments', 'schedules', 'quick_links'] loop
    execute format('drop policy if exists %I on harim_nexus.%I', table_name || '_workspace_read', table_name);
    execute format(
      'create policy %I on harim_nexus.%I for select to authenticated using ((select harim_nexus_private.has_workspace_access(workspace_id, null)))',
      table_name || '_workspace_read', table_name
    );
  end loop;
end $$;

-- 본인 프로필(이름·직위·부서·한마디·스킬·상태)은 직접 수정. 역할·승인·아이디는 관리자만(서버 라우트)
grant update (name, position, department, message, skills, status) on harim_nexus.members to authenticated;


-- ============================================================
-- 10. 명시적 권한 (Data API 기본 권한에 의존하지 않는다)
-- ============================================================
grant all on all tables in schema harim_nexus to service_role;
grant all on all sequences in schema harim_nexus to service_role;
grant execute on all functions in schema harim_nexus to service_role;
grant usage, select on all sequences in schema harim_nexus to authenticated;
grant usage on schema harim_nexus_private to service_role;
grant execute on all functions in schema harim_nexus_private to service_role;
