-- 01_nexus_schema.sql 적용 후 SQL Editor에서 실행. public/Auth/Storage는 변경하지 않는다.
-- 다시 실행 가능. 기존 완료 업무의 완료일은 알 수 없으므로 역산하지 않는다.
begin;

alter table harim_nexus.tasks
  add column if not exists completed_at timestamptz,
  add column if not exists updated_at timestamptz not null default now(),
  add column if not exists requested_by_member_id bigint references harim_nexus.members(id) on delete set null,
  add column if not exists accepted_at timestamptz,
  add column if not exists source text not null default 'manual',
  add column if not exists source_ref text,
  add column if not exists closing_run_id bigint;
-- closing_runs의 FK는 P2에서 추가한다.
alter table harim_nexus.workspace_settings
  add column if not exists ai_guidelines text not null default '',
  add column if not exists ai_enabled boolean not null default false,
  add column if not exists ai_mask_numbers boolean not null default true,
  add column if not exists ai_daily_limit integer not null default 10 check (ai_daily_limit between 1 and 100),
  add column if not exists ai_monthly_token_budget bigint not null default 1000000 check (ai_monthly_token_budget between 1000 and 100000000);

create table if not exists harim_nexus.weekly_reports (
  id bigint generated by default as identity primary key,
  workspace_id uuid not null references harim_nexus.workspaces(id) on delete cascade,
  member_id bigint not null references harim_nexus.members(id) on delete cascade,
  week_start date not null check (extract(isodow from week_start) = 1),
  content jsonb not null default '{}'::jsonb,
  status text not null default 'draft' check (status in ('draft','submitted')),
  submitted_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique(workspace_id, member_id, week_start)
);
create table if not exists harim_nexus.ai_reviews (
  id bigint generated by default as identity primary key,
  workspace_id uuid not null references harim_nexus.workspaces(id) on delete cascade,
  entity_type text not null check (entity_type in ('task','weekly_report')),
  entity_id bigint not null,
  member_id bigint not null references harim_nexus.members(id) on delete cascade,
  trigger_type text not null check (trigger_type in ('completed','delayed','weekly_submitted','closing_item')),
  source_version timestamptz not null,
  source_snapshot jsonb not null,
  status text not null default 'queued' check (status in ('queued','processing','questions','awaiting_confirmation','confirmed','failed','superseded')),
  round integer not null default 0 check (round between 0 and 2),
  summary jsonb,
  risk_level text check (risk_level in ('low','medium','high')),
  model text,
  input_tokens bigint not null default 0,
  output_tokens bigint not null default 0,
  error_message text,
  lease_id uuid,
  processing_at timestamptz,
  confirmed_at timestamptz,
  created_at timestamptz not null default now(),
  unique(entity_type, entity_id, source_version, member_id)
);
create table if not exists harim_nexus.ai_review_messages (
  id bigint generated by default as identity primary key,
  review_id bigint not null references harim_nexus.ai_reviews(id) on delete cascade,
  role text not null check (role in ('assistant','user')),
  content jsonb not null,
  created_at timestamptz not null default now()
);
-- 실제 응답 토큰과 불확실한 시도의 보수적 예약량을 함께 기록한다.
create table if not exists harim_nexus.ai_call_usage (
  id bigint generated by default as identity primary key,
  workspace_id uuid not null references harim_nexus.workspaces(id) on delete cascade,
  member_id bigint not null references harim_nexus.members(id) on delete cascade,
  review_id bigint not null references harim_nexus.ai_reviews(id) on delete cascade,
  reserved_tokens bigint not null check (reserved_tokens > 0),
  input_tokens bigint,
  output_tokens bigint,
  created_at timestamptz not null default now()
);
create index if not exists idx_weekly_workspace_week on harim_nexus.weekly_reports(workspace_id,week_start);
create index if not exists idx_ai_member_status on harim_nexus.ai_reviews(workspace_id,member_id,status,created_at desc);
create index if not exists idx_ai_entity on harim_nexus.ai_reviews(entity_type,entity_id);
create index if not exists idx_ai_messages_review on harim_nexus.ai_review_messages(review_id,id);
create index if not exists idx_ai_usage_month on harim_nexus.ai_call_usage(workspace_id,created_at);
create index if not exists idx_tasks_completed on harim_nexus.tasks(workspace_id,assignee_member_id,completed_at) where deleted_at is null;

alter table harim_nexus.weekly_reports enable row level security;
alter table harim_nexus.ai_reviews enable row level security;
alter table harim_nexus.ai_review_messages enable row level security;
alter table harim_nexus.ai_call_usage enable row level security;
revoke all on harim_nexus.weekly_reports,harim_nexus.ai_reviews,harim_nexus.ai_review_messages,harim_nexus.ai_call_usage from public,anon,authenticated;
grant select on harim_nexus.weekly_reports,harim_nexus.ai_reviews,harim_nexus.ai_review_messages to authenticated;
grant all on harim_nexus.weekly_reports,harim_nexus.ai_reviews,harim_nexus.ai_review_messages,harim_nexus.ai_call_usage to service_role;
grant usage,select on sequence harim_nexus.weekly_reports_id_seq,harim_nexus.ai_reviews_id_seq,harim_nexus.ai_review_messages_id_seq,harim_nexus.ai_call_usage_id_seq to service_role;

drop policy if exists weekly_read on harim_nexus.weekly_reports;
create policy weekly_read on harim_nexus.weekly_reports for select to authenticated using (
  harim_nexus_private.has_workspace_access(workspace_id,null) and
  (member_id = harim_nexus_private.current_nexus_member_id() or
    (status = 'submitted' and (harim_nexus_private.is_nexus_admin() or harim_nexus_private.has_workspace_access(workspace_id,array['owner','admin']))))
);
drop policy if exists ai_read on harim_nexus.ai_reviews;
create policy ai_read on harim_nexus.ai_reviews for select to authenticated using (
  harim_nexus_private.has_workspace_access(workspace_id,null) and
  (member_id = harim_nexus_private.current_nexus_member_id() or
    (status = 'confirmed' and (harim_nexus_private.is_nexus_admin() or harim_nexus_private.has_workspace_access(workspace_id,array['owner','admin']))))
);
drop policy if exists ai_messages_read on harim_nexus.ai_review_messages;
create policy ai_messages_read on harim_nexus.ai_review_messages for select to authenticated using (
  exists(select 1 from harim_nexus.ai_reviews r where r.id=review_id and r.member_id=harim_nexus_private.current_nexus_member_id())
);

create or replace function harim_nexus_private.p1_task_stamp()
returns trigger language plpgsql security invoker set search_path='' as $$
begin
  new.updated_at := clock_timestamp();
  if tg_op='INSERT' then
    new.completed_at := case when new.status='완료' then now() else null end;
    new.requested_by_member_id := coalesce(harim_nexus_private.current_nexus_member_id(),new.created_by_member_id);
  else
    if new.status is distinct from old.status then
      new.completed_at := case when new.status='완료' then now() else null end;
    else new.completed_at := old.completed_at;
    end if;
    if new.assignee_member_id is distinct from old.assignee_member_id then
      new.requested_by_member_id := coalesce(harim_nexus_private.current_nexus_member_id(),new.created_by_member_id);
      new.accepted_at := null;
    else new.requested_by_member_id := old.requested_by_member_id;
    end if;
  end if;
  return new;
end $$;
drop trigger if exists p1_task_stamp on harim_nexus.tasks;
create trigger p1_task_stamp before insert or update on harim_nexus.tasks for each row execute function harim_nexus_private.p1_task_stamp();

-- 서버 외부 요청 없이 알림·AI 대기 기록을 원 업무와 같은 트랜잭션에 저장한다.
create or replace function harim_nexus_private.p1_task_events()
returns trigger language plpgsql security definer set search_path='' as $$
declare actor bigint; changed boolean; reason text;
begin
  actor := harim_nexus_private.current_nexus_member_id();
  changed := tg_op='INSERT';
  if tg_op='UPDATE' then
    changed := new.assignee_member_id is distinct from old.assignee_member_id;
    update harim_nexus.ai_reviews set status='superseded',lease_id=null
      where entity_type='task' and entity_id=new.id and status<>'superseded';
  end if;
  if new.deleted_at is not null then return new; end if;
  if changed and new.assignee_member_id is not null and new.assignee_member_id is distinct from actor then
    insert into harim_nexus.notifications(workspace_id,recipient_member_id,actor_member_id,kind,title,entity_type,entity_id,action_url)
    values(new.workspace_id,new.assignee_member_id,actor,'assignment','업무가 배정되었습니다: '||coalesce(new.title,''),'task',new.id::text,'/kanban?task='||new.id);
  end if;
  if new.status='완료' then
    reason := case when new.closing_run_id is not null then 'closing_item' else 'completed' end;
    if tg_op='INSERT' or old.status is distinct from new.status then
      insert into harim_nexus.notifications(workspace_id,recipient_member_id,actor_member_id,kind,title,entity_type,entity_id,action_url)
      select new.workspace_id,m.id,actor,'status','업무가 완료되었습니다: '||coalesce(new.title,''),'task',new.id::text,'/kanban?task='||new.id
      from harim_nexus.members m join harim_nexus.workspace_members wm on wm.member_id=m.id and wm.workspace_id=new.workspace_id
      where wm.active and m.approved and m.status<>'pending' and m.id is distinct from actor
        and (m.id=new.requested_by_member_id or m.role='admin' or wm.role in ('owner','admin'));
    end if;
  elsif coalesce(new.delay_reason,'')<>'' or (new.due_date < to_char(now() at time zone 'Asia/Seoul','YYYY-MM-DD')) then
    reason := 'delayed';
  end if;
  if reason is not null and new.assignee_member_id is not null then
    insert into harim_nexus.ai_reviews(workspace_id,entity_type,entity_id,member_id,trigger_type,source_version,source_snapshot)
    values(new.workspace_id,'task',new.id,new.assignee_member_id,reason,new.updated_at,
      jsonb_build_object('title',new.title,'content',new.content,'status',new.status,'due_date',new.due_date,'delay_reason',new.delay_reason,'deliverable_url',new.deliverable_url,'acceptance_criteria',new.acceptance_criteria))
    on conflict do nothing;
  end if;
  return new;
end $$;
drop trigger if exists p1_task_events on harim_nexus.tasks;
create trigger p1_task_events after insert or update on harim_nexus.tasks for each row execute function harim_nexus_private.p1_task_events();

create or replace function harim_nexus_private.p1_comment_event()
returns trigger language plpgsql security definer set search_path='' as $$
begin
  if new.entity_type='task' and new.deleted_at is null then
    insert into harim_nexus.notifications(workspace_id,recipient_member_id,actor_member_id,kind,title,body,entity_type,entity_id,action_url)
    select t.workspace_id,t.assignee_member_id,new.author_member_id,'comment','내 업무에 댓글이 달렸습니다: '||coalesce(t.title,''),left(new.content,240),'task',t.id::text,'/kanban?task='||t.id
    from harim_nexus.tasks t where t.id=new.entity_id and t.workspace_id=new.workspace_id and t.deleted_at is null
      and t.assignee_member_id is not null and t.assignee_member_id is distinct from new.author_member_id;
  end if;
  return new;
end $$;
drop trigger if exists p1_comment_event on harim_nexus.comments;
create trigger p1_comment_event after insert on harim_nexus.comments for each row execute function harim_nexus_private.p1_comment_event();
revoke all on function harim_nexus_private.p1_task_events(),harim_nexus_private.p1_comment_event(),harim_nexus_private.p1_task_stamp() from public,anon,authenticated;

-- 서버 API만 호출: 인증된 호출자의 member_id를 전달한다. 브라우저 DML은 허용하지 않는다.
create or replace function harim_nexus.nexus_save_weekly(p_workspace uuid,p_member bigint,p_week date,p_content jsonb,p_submit boolean,p_version timestamptz)
returns harim_nexus.weekly_reports language plpgsql security invoker set search_path='' as $$
declare r harim_nexus.weekly_reports; previous_status text;
begin
  perform pg_advisory_xact_lock(hashtextextended(p_workspace::text||':'||p_member||':'||p_week,0));
  select * into r from harim_nexus.weekly_reports where workspace_id=p_workspace and member_id=p_member and week_start=p_week for update;
  if (r.id is not null and r.updated_at is distinct from p_version) or (r.id is null and p_version is not null) then
    raise exception '다른 창에서 보고서를 수정했습니다. 새로 불러와 주세요.';
  end if;
  previous_status := r.status;
  insert into harim_nexus.weekly_reports(workspace_id,member_id,week_start,content,status,submitted_at)
  values(p_workspace,p_member,p_week,p_content,case when p_submit then 'submitted' else 'draft' end,case when p_submit then now() end)
  on conflict(workspace_id,member_id,week_start) do update set content=excluded.content,status=excluded.status,submitted_at=excluded.submitted_at,updated_at=clock_timestamp()
  returning * into r;
  update harim_nexus.ai_reviews set status='superseded',lease_id=null where entity_type='weekly_report' and entity_id=r.id and status<>'superseded';
  if p_submit then
    insert into harim_nexus.ai_reviews(workspace_id,entity_type,entity_id,member_id,trigger_type,source_version,source_snapshot)
    values(p_workspace,'weekly_report',r.id,p_member,'weekly_submitted',r.updated_at,jsonb_build_object('week_start',p_week,'content',p_content));
    if previous_status is distinct from 'submitted' then
      insert into harim_nexus.notifications(workspace_id,recipient_member_id,actor_member_id,kind,title,entity_type,entity_id,action_url)
      select p_workspace,m.id,p_member,'system','주간보고가 제출되었습니다.','weekly_report',r.id::text,'/weekly?week='||p_week
      from harim_nexus.members m join harim_nexus.workspace_members wm on wm.member_id=m.id and wm.workspace_id=p_workspace
      where wm.active and m.approved and m.status<>'pending' and m.id<>p_member and (m.role='admin' or wm.role in ('owner','admin'));
    end if;
  end if;
  return r;
end $$;

create or replace function harim_nexus.nexus_ai_transition(p_id bigint,p_member bigint,p_action text,p_answers jsonb default null)
returns harim_nexus.ai_reviews language plpgsql security invoker set search_path='' as $$
declare r harim_nexus.ai_reviews; questions jsonb;
begin
  select * into r from harim_nexus.ai_reviews where id=p_id and member_id=p_member for update;
  if r.id is null then raise exception '내 AI 검토만 처리할 수 있습니다.'; end if;
  if p_action='confirm' then
    if r.status<>'awaiting_confirmation' then raise exception '확인 가능한 요약이 아닙니다.'; end if;
    update harim_nexus.ai_reviews set status='confirmed',confirmed_at=now() where id=p_id returning * into r;
    if r.risk_level='high' then
      insert into harim_nexus.notifications(workspace_id,recipient_member_id,actor_member_id,kind,title,body,entity_type,entity_id,action_url)
      select r.workspace_id,m.id,p_member,'system','확인된 고위험 업무가 있습니다.',left(r.summary->>'risks',240),'ai_review',r.id::text,'/ai?review='||r.id
      from harim_nexus.members m join harim_nexus.workspace_members wm on wm.member_id=m.id and wm.workspace_id=r.workspace_id
      where wm.active and m.approved and m.status<>'pending' and (m.role='admin' or wm.role in ('owner','admin'));
    end if;
    return r;
  end if;
  if p_action='answer' then
    if r.status<>'questions' then raise exception '답변할 질문이 없습니다.'; end if;
    select content->'questions' into questions from harim_nexus.ai_review_messages where review_id=p_id and role='assistant' order by id desc limit 1;
    if jsonb_typeof(p_answers) is distinct from 'array' or jsonb_array_length(p_answers) is distinct from jsonb_array_length(questions) then raise exception '모든 질문에 답변해 주세요.'; end if;
    if exists(select 1 from jsonb_array_elements(p_answers) a where jsonb_typeof(a)<>'string' or length(trim(a#>>'{}')) not between 1 and 3000) then raise exception '답변은 질문마다 1~3000자로 작성해 주세요.'; end if;
    insert into harim_nexus.ai_review_messages(review_id,role,content) values(p_id,'user',p_answers);
  elsif p_action<>'run' or not (r.status in ('queued','failed') or (r.status='processing' and r.processing_at<now()-interval '2 minutes')) then
    raise exception '이미 처리 중이거나 종료된 검토입니다.';
  end if;
  update harim_nexus.ai_reviews set status='processing',processing_at=now(),lease_id=gen_random_uuid(),error_message=null where id=p_id returning * into r;
  return r;
end $$;

create or replace function harim_nexus.nexus_reserve_ai_call(p_id bigint,p_lease uuid,p_tokens bigint)
returns bigint language plpgsql security invoker set search_path='' as $$
declare r harim_nexus.ai_reviews; s harim_nexus.workspace_settings; used bigint; calls bigint; call_id bigint;
begin
  select * into r from harim_nexus.ai_reviews where id=p_id and status='processing' and lease_id=p_lease;
  if r.id is null then raise exception 'AI 검토 버전이 변경되었습니다.'; end if;
  select * into s from harim_nexus.workspace_settings where workspace_id=r.workspace_id for update;
  if not coalesce(s.ai_enabled,false) then raise exception '관리자가 AI 외부 전송을 활성화해야 합니다.'; end if;
  select count(*) into calls from harim_nexus.ai_call_usage where workspace_id=r.workspace_id and member_id=r.member_id and created_at >= (date_trunc('day',now() at time zone 'Asia/Seoul') at time zone 'Asia/Seoul');
  select coalesce(sum(coalesce(input_tokens+output_tokens,reserved_tokens)),0) into used from harim_nexus.ai_call_usage where workspace_id=r.workspace_id and created_at >= (date_trunc('month',now() at time zone 'Asia/Seoul') at time zone 'Asia/Seoul');
  if calls>=s.ai_daily_limit then raise exception '오늘의 AI 호출 상한에 도달했습니다.'; end if;
  if p_tokens<1 or used+p_tokens>s.ai_monthly_token_budget then raise exception '월 AI 토큰 예산이 부족합니다.'; end if;
  insert into harim_nexus.ai_call_usage(workspace_id,member_id,review_id,reserved_tokens) values(r.workspace_id,r.member_id,r.id,p_tokens) returning id into call_id;
  return call_id;
end $$;

create or replace function harim_nexus.nexus_finish_ai_review(p_id bigint,p_lease uuid,p_result jsonb,p_error text default null)
returns boolean language plpgsql security invoker set search_path='' as $$
declare r harim_nexus.ai_reviews;
begin
  select * into r from harim_nexus.ai_reviews where id=p_id and status='processing' and lease_id=p_lease for update;
  if r.id is null then return false; end if;
  if p_error is not null then
    update harim_nexus.ai_reviews set status='failed',error_message=left(p_error,300),lease_id=null where id=p_id;
    return true;
  end if;
  insert into harim_nexus.ai_review_messages(review_id,role,content) values(p_id,'assistant',p_result);
  update harim_nexus.ai_reviews set
    status=case when jsonb_array_length(p_result->'questions')>0 then 'questions' else 'awaiting_confirmation' end,
    round=r.round+case when jsonb_array_length(p_result->'questions')>0 then 1 else 0 end,
    summary=p_result->'summary',risk_level=p_result->>'risk_level',model=p_result->>'model',lease_id=null,
    input_tokens=(select coalesce(sum(input_tokens),0) from harim_nexus.ai_call_usage where review_id=p_id),
    output_tokens=(select coalesce(sum(output_tokens),0) from harim_nexus.ai_call_usage where review_id=p_id)
  where id=p_id;
  return true;
end $$;

revoke all on function harim_nexus.nexus_save_weekly(uuid,bigint,date,jsonb,boolean,timestamptz),harim_nexus.nexus_ai_transition(bigint,bigint,text,jsonb),harim_nexus.nexus_reserve_ai_call(bigint,uuid,bigint),harim_nexus.nexus_finish_ai_review(bigint,uuid,jsonb,text) from public,anon,authenticated;
grant execute on function harim_nexus.nexus_save_weekly(uuid,bigint,date,jsonb,boolean,timestamptz),harim_nexus.nexus_ai_transition(bigint,bigint,text,jsonb),harim_nexus.nexus_reserve_ai_call(bigint,uuid,bigint),harim_nexus.nexus_finish_ai_review(bigint,uuid,jsonb,text) to service_role;
notify pgrst,'reload schema';
commit;
