-- P2: 월마감 템플릿·실행 + Google Chat 알림 + 구글 캘린더 구독(ICS)
-- 01, 02 적용 후 SQL Editor 에서 실행. 다시 실행해도 안전하다. public/Auth/Storage 는 변경하지 않는다.
begin;

-- ------------------------------------------------------------
-- 1. 공휴일 · Google Chat 설정 (워크스페이스 설정)
-- ------------------------------------------------------------
alter table harim_nexus.workspace_settings
  -- 영업일 계산용 공휴일(대체공휴일 포함). /closing 관리자 화면에서 고친다. 음력·임시공휴일은 발표 확인 필요.
  add column if not exists holidays date[] not null default array[
    '2026-10-05','2026-10-09','2026-12-25',
    '2027-01-01','2027-02-08','2027-02-09','2027-03-01','2027-05-05','2027-05-13',
    '2027-08-16','2027-09-14','2027-09-15','2027-09-16','2027-10-04','2027-10-11','2027-12-27'
  ]::date[],
  add column if not exists chat_enabled boolean not null default false,
  add column if not exists chat_enabled_at timestamptz,
  add column if not exists chat_mention_by_email boolean not null default false,
  add column if not exists chat_last_brief_date date;

-- 알림을 Chat 으로 보냈는지 기록 (중복 전송 방지)
alter table harim_nexus.notifications add column if not exists chat_sent_at timestamptz;
create index if not exists idx_notifications_chat_pending on harim_nexus.notifications(created_at) where chat_sent_at is null;

-- ------------------------------------------------------------
-- 2. 월마감 템플릿 · 항목 · 실행
-- ------------------------------------------------------------
create table if not exists harim_nexus.closing_templates (
  id bigint generated by default as identity primary key,
  workspace_id uuid not null default '00000000-0000-4000-8000-000000000001' references harim_nexus.workspaces(id) on delete cascade,
  name text not null check (length(trim(name)) between 1 and 100),
  description text not null default '' check (length(description) <= 2000),
  active boolean not null default true,
  auto_start boolean not null default false,
  created_by_member_id bigint references harim_nexus.members(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (workspace_id, name)
);

create table if not exists harim_nexus.closing_template_items (
  id bigint generated by default as identity primary key,
  template_id bigint not null references harim_nexus.closing_templates(id) on delete cascade,
  title text not null check (length(trim(title)) between 1 and 200),
  description text not null default '' check (length(description) <= 4000),
  offset_days integer not null default 0 check (offset_days between 0 and 30),
  default_assignee_member_id bigint references harim_nexus.members(id) on delete set null,
  reference_url text check (reference_url is null or reference_url ~ '^https?://'),
  sort_order integer not null default 0,
  created_at timestamptz not null default now()
);
create index if not exists idx_closing_items_template on harim_nexus.closing_template_items(template_id, sort_order);
create index if not exists idx_closing_items_assignee on harim_nexus.closing_template_items(default_assignee_member_id);

create table if not exists harim_nexus.closing_runs (
  id bigint generated by default as identity primary key,
  workspace_id uuid not null default '00000000-0000-4000-8000-000000000001' references harim_nexus.workspaces(id) on delete cascade,
  template_id bigint not null references harim_nexus.closing_templates(id) on delete restrict,
  period text not null check (period ~ '^\d{4}-(0[1-9]|1[0-2])$'),
  start_date date not null,
  status text not null default 'open' check (status in ('open', 'closed')),
  created_by_member_id bigint references harim_nexus.members(id) on delete set null,
  created_at timestamptz not null default now(),
  closed_at timestamptz,
  unique (template_id, period)
);
create index if not exists idx_closing_runs_workspace on harim_nexus.closing_runs(workspace_id, period desc);
create index if not exists idx_closing_runs_creator on harim_nexus.closing_runs(created_by_member_id);

alter table harim_nexus.tasks add column if not exists closing_item_id bigint references harim_nexus.closing_template_items(id) on delete set null;
create index if not exists idx_tasks_closing_run on harim_nexus.tasks(closing_run_id) where closing_run_id is not null;
create index if not exists idx_tasks_closing_item on harim_nexus.tasks(closing_item_id) where closing_item_id is not null;
do $$
begin
  if not exists (select 1 from pg_constraint where conname = 'tasks_closing_run_id_fkey') then
    alter table harim_nexus.tasks add constraint tasks_closing_run_id_fkey
      foreign key (closing_run_id) references harim_nexus.closing_runs(id) on delete set null;
  end if;
end $$;

-- ------------------------------------------------------------
-- 3. 구글 캘린더 구독 토큰 (서버 전용 — 다른 팀원이 읽을 수 없게 별도 표)
-- ------------------------------------------------------------
create table if not exists harim_nexus.member_calendar_tokens (
  member_id bigint primary key references harim_nexus.members(id) on delete cascade,
  token uuid not null unique default gen_random_uuid(),
  created_at timestamptz not null default now()
);

-- ------------------------------------------------------------
-- 4. 권한: 월마감은 구성원 누구나 읽기, 변경은 서버(관리자 검증) 전용
-- ------------------------------------------------------------
alter table harim_nexus.closing_templates enable row level security;
alter table harim_nexus.closing_template_items enable row level security;
alter table harim_nexus.closing_runs enable row level security;
alter table harim_nexus.member_calendar_tokens enable row level security;

drop policy if exists closing_templates_read on harim_nexus.closing_templates;
create policy closing_templates_read on harim_nexus.closing_templates for select to authenticated
using ((select harim_nexus_private.has_workspace_access(workspace_id, null)));
drop policy if exists closing_items_read on harim_nexus.closing_template_items;
create policy closing_items_read on harim_nexus.closing_template_items for select to authenticated
using (exists (select 1 from harim_nexus.closing_templates t where t.id = template_id
  and (select harim_nexus_private.has_workspace_access(t.workspace_id, null))));
drop policy if exists closing_runs_read on harim_nexus.closing_runs;
create policy closing_runs_read on harim_nexus.closing_runs for select to authenticated
using ((select harim_nexus_private.has_workspace_access(workspace_id, null)));
-- member_calendar_tokens: 정책 없음 = authenticated 접근 불가 (service_role 만)

revoke all on harim_nexus.closing_templates, harim_nexus.closing_template_items, harim_nexus.closing_runs,
  harim_nexus.member_calendar_tokens from public, anon, authenticated;
grant select on harim_nexus.closing_templates, harim_nexus.closing_template_items, harim_nexus.closing_runs to authenticated;
grant all on harim_nexus.closing_templates, harim_nexus.closing_template_items, harim_nexus.closing_runs,
  harim_nexus.member_calendar_tokens to service_role;
grant usage, select on sequence harim_nexus.closing_templates_id_seq, harim_nexus.closing_template_items_id_seq,
  harim_nexus.closing_runs_id_seq to service_role;

-- ------------------------------------------------------------
-- 5. 월마감 실행 생성: 실행 1건 + 업무 N건을 한 트랜잭션으로
--    (업무 배정 알림·완료 시 AI 검토는 02 의 업무 트리거가 그대로 처리한다)
-- ------------------------------------------------------------
create or replace function harim_nexus.nexus_create_closing_run(
  p_workspace uuid, p_template bigint, p_period text, p_start date, p_actor bigint, p_tasks jsonb
) returns harim_nexus.closing_runs language plpgsql security invoker set search_path = '' as $$
declare r harim_nexus.closing_runs;
begin
  if jsonb_typeof(p_tasks) is distinct from 'array' or jsonb_array_length(p_tasks) = 0 then
    raise exception '월마감 항목이 없습니다.';
  end if;
  if not exists (select 1 from harim_nexus.closing_templates where id = p_template and workspace_id = p_workspace and active) then
    raise exception '사용 중인 월마감 템플릿이 아닙니다.';
  end if;
  begin
    insert into harim_nexus.closing_runs(workspace_id, template_id, period, start_date, created_by_member_id)
    values (p_workspace, p_template, p_period, p_start, p_actor) returning * into r;
  exception when unique_violation then
    raise exception '이미 시작된 월마감입니다: %', p_period;
  end;
  insert into harim_nexus.tasks(workspace_id, title, content, status, priority, assignee, assignee_member_id,
    due_date, start_date, source, source_ref, closing_run_id, closing_item_id, created_by_member_id)
  select p_workspace, left(t->>'title', 300), coalesce(t->>'content', ''), '대기', '보통', t->>'assignee',
    nullif(t->>'assignee_member_id', '')::bigint, t->>'due_date', p_start, 'closing', p_period, r.id,
    nullif(t->>'item_id', '')::bigint, p_actor
  from jsonb_array_elements(p_tasks) t;
  return r;
end $$;

-- ------------------------------------------------------------
-- 6. Chat 으로 보낼 알림을 집어 오기 (동시 실행돼도 한 번만 보냄)
-- ------------------------------------------------------------
create or replace function harim_nexus.nexus_claim_chat_notifications(p_workspace uuid, p_kinds text[], p_limit integer)
returns setof harim_nexus.notifications language plpgsql security invoker set search_path = '' as $$
declare since timestamptz;
begin
  select chat_enabled_at into since from harim_nexus.workspace_settings where workspace_id = p_workspace and chat_enabled;
  if since is null then return; end if;
  return query
  update harim_nexus.notifications n set chat_sent_at = now()
  where n.id in (
    select id from harim_nexus.notifications
    where workspace_id = p_workspace and chat_sent_at is null and kind = any(p_kinds)
      and created_at >= greatest(since, now() - interval '1 day')
    order by id limit least(greatest(p_limit, 1), 50)
    for update skip locked
  )
  returning n.*;
end $$;

-- 아침 브리핑 중복 방지: 오늘 처음 호출한 경우에만 true
create or replace function harim_nexus.nexus_claim_daily_brief(p_workspace uuid, p_date date)
returns boolean language plpgsql security invoker set search_path = '' as $$
declare claimed boolean;
begin
  update harim_nexus.workspace_settings set chat_last_brief_date = p_date
  where workspace_id = p_workspace and chat_enabled and chat_last_brief_date is distinct from p_date
  returning true into claimed;
  return coalesce(claimed, false);
end $$;

revoke all on function harim_nexus.nexus_create_closing_run(uuid, bigint, text, date, bigint, jsonb),
  harim_nexus.nexus_claim_chat_notifications(uuid, text[], integer),
  harim_nexus.nexus_claim_daily_brief(uuid, date) from public, anon, authenticated;
grant execute on function harim_nexus.nexus_create_closing_run(uuid, bigint, text, date, bigint, jsonb),
  harim_nexus.nexus_claim_chat_notifications(uuid, text[], integer),
  harim_nexus.nexus_claim_daily_brief(uuid, date) to service_role;

-- ------------------------------------------------------------
-- 7. 알림 실시간 수신 (헤더 종 아이콘). Supabase Realtime 이 RLS 를 적용한다.
-- ------------------------------------------------------------
do $$
begin
  if exists (select 1 from pg_publication where pubname = 'supabase_realtime')
     and not exists (select 1 from pg_publication_tables where pubname = 'supabase_realtime'
                     and schemaname = 'harim_nexus' and tablename = 'notifications') then
    alter publication supabase_realtime add table harim_nexus.notifications;
  end if;
end $$;

commit;
