-- 04: AI 친구 완료 점검 + 팀장 검토
-- 01·02·03 적용 후 SQL Editor 에서 실행. 다시 실행해도 안전. public/Auth/Storage 는 변경하지 않는다.
-- 흐름: 완료 버튼 → AI 친구 점검 질문(draft) → 답변 제출 시 업무 완료(submitted) → 팀장 확인(approved) 또는 보완 요청(returned, 업무는 진행중으로)
begin;

create table if not exists harim_nexus.task_completion_checks (
  id bigint generated by default as identity primary key,
  workspace_id uuid not null references harim_nexus.workspaces(id) on delete cascade,
  task_id bigint not null references harim_nexus.tasks(id) on delete cascade,
  member_id bigint not null references harim_nexus.members(id) on delete cascade, -- 완료 처리한 사람
  task_version timestamptz not null,
  task_snapshot jsonb not null,
  questions jsonb not null check (jsonb_typeof(questions) = 'array' and jsonb_array_length(questions) between 1 and 5),
  answers jsonb,
  question_source text not null check (question_source in ('ai','default')),
  model text,
  status text not null default 'draft' check (status in ('draft','submitted','approved','returned','superseded')),
  lead_comment text check (lead_comment is null or length(lead_comment) <= 3000),
  reviewed_by_member_id bigint references harim_nexus.members(id) on delete set null,
  reviewed_at timestamptz,
  submitted_at timestamptz,
  created_at timestamptz not null default now(),
  unique(task_id, member_id, task_version)
);
create index if not exists idx_checks_status on harim_nexus.task_completion_checks(workspace_id,status,submitted_at desc);
create index if not exists idx_checks_member on harim_nexus.task_completion_checks(workspace_id,member_id,created_at desc);
create index if not exists idx_checks_task on harim_nexus.task_completion_checks(task_id,created_at desc);

alter table harim_nexus.task_completion_checks enable row level security;
revoke all on harim_nexus.task_completion_checks from public,anon,authenticated;
grant select on harim_nexus.task_completion_checks to authenticated;
grant all on harim_nexus.task_completion_checks to service_role;
grant usage,select on sequence harim_nexus.task_completion_checks_id_seq to service_role;
drop policy if exists checks_read on harim_nexus.task_completion_checks;
create policy checks_read on harim_nexus.task_completion_checks for select to authenticated using (
  harim_nexus_private.has_workspace_access(workspace_id,null) and
  (member_id = harim_nexus_private.current_nexus_member_id() or harim_nexus_private.is_nexus_admin()
    or harim_nexus_private.has_workspace_access(workspace_id,array['owner','admin']))
);

-- 완료 점검 질문 호출도 같은 일·월 AI 한도를 쓴다.
alter table harim_nexus.ai_call_usage alter column review_id drop not null;
alter table harim_nexus.ai_call_usage add column if not exists check_id bigint references harim_nexus.task_completion_checks(id) on delete cascade;

-- 브라우저(authenticated)에서 점검 없이 '완료'로 바꾸는 것을 막는다. 서버(service_role)의 점검 제출 RPC만 완료시킨다.
create or replace function harim_nexus_private.p1_task_stamp()
returns trigger language plpgsql security invoker set search_path='' as $$
begin
  if new.status='완료' and (tg_op='INSERT' or old.status is distinct from '완료') and current_user='authenticated' then
    raise exception 'AI 친구 완료 점검을 거쳐야 완료할 수 있습니다. 화면을 새로고침한 뒤 완료 버튼을 다시 눌러 주세요.' using errcode='P0001';
  end if;
  new.updated_at := clock_timestamp();
  if tg_op='INSERT' then
    new.completed_at := case when new.status='완료' then now() else null end;
    new.requested_by_member_id := coalesce(harim_nexus_private.current_nexus_member_id(),new.created_by_member_id);
  else
    if new.status is distinct from old.status then
      new.completed_at := case when new.status='완료' then now() else null end;
    else new.completed_at := old.completed_at;
    end if;
    if new.assignee_member_id is distinct from old.assignee_member_id then
      new.requested_by_member_id := coalesce(harim_nexus_private.current_nexus_member_id(),new.created_by_member_id);
      new.accepted_at := null;
    else new.requested_by_member_id := old.requested_by_member_id;
    end if;
  end if;
  return new;
end $$;

-- 완료 시 AI 대기열(ai_reviews) 대신 완료 점검을 쓴다. 지연 기록 정리는 그대로 둔다.
-- 서버 RPC 는 로그인 사용자가 없으므로 harim_nexus.actor 설정값으로 행위자를 넘긴다.
create or replace function harim_nexus_private.p1_task_events()
returns trigger language plpgsql security definer set search_path='' as $$
declare actor bigint; changed boolean;
begin
  actor := coalesce(harim_nexus_private.current_nexus_member_id(), nullif(current_setting('harim_nexus.actor', true),'')::bigint);
  changed := tg_op='INSERT';
  if tg_op='UPDATE' then
    changed := new.assignee_member_id is distinct from old.assignee_member_id;
    update harim_nexus.ai_reviews set status='superseded',lease_id=null
      where entity_type='task' and entity_id=new.id and status<>'superseded';
    -- 완료가 풀리거나 삭제되면 검토 대기 점검은 제외 (팀장 보완 요청은 먼저 returned 가 되어 영향 없음)
    if (old.status='완료' and new.status is distinct from '완료') or (new.deleted_at is not null and old.deleted_at is null) then
      update harim_nexus.task_completion_checks set status='superseded'
        where task_id=new.id and status in ('draft','submitted');
    end if;
  end if;
  if new.deleted_at is not null then return new; end if;
  if changed and new.assignee_member_id is not null and new.assignee_member_id is distinct from actor then
    insert into harim_nexus.notifications(workspace_id,recipient_member_id,actor_member_id,kind,title,entity_type,entity_id,action_url)
    values(new.workspace_id,new.assignee_member_id,actor,'assignment','업무가 배정되었습니다: '||coalesce(new.title,''),'task',new.id::text,'/kanban?task='||new.id);
  end if;
  if new.status='완료' then
    if tg_op='INSERT' or old.status is distinct from new.status then
      insert into harim_nexus.notifications(workspace_id,recipient_member_id,actor_member_id,kind,title,entity_type,entity_id,action_url)
      select new.workspace_id,m.id,actor,'status',
        case when m.role='admin' or wm.role in ('owner','admin') then '완료 점검을 검토해 주세요: ' else '업무가 완료되었습니다: ' end||coalesce(new.title,''),
        'task',new.id::text,
        case when m.role='admin' or wm.role in ('owner','admin') then '/ai?task='||new.id else '/kanban?task='||new.id end
      from harim_nexus.members m join harim_nexus.workspace_members wm on wm.member_id=m.id and wm.workspace_id=new.workspace_id
      where wm.active and m.approved and m.status<>'pending' and m.id is distinct from actor
        and (m.id=new.requested_by_member_id or m.role='admin' or wm.role in ('owner','admin'));
    end if;
  elsif new.assignee_member_id is not null and (coalesce(new.delay_reason,'')<>'' or (new.due_date < to_char(now() at time zone 'Asia/Seoul','YYYY-MM-DD'))) then
    insert into harim_nexus.ai_reviews(workspace_id,entity_type,entity_id,member_id,trigger_type,source_version,source_snapshot)
    values(new.workspace_id,'task',new.id,new.assignee_member_id,'delayed',new.updated_at,
      jsonb_build_object('title',new.title,'content',new.content,'status',new.status,'due_date',new.due_date,'delay_reason',new.delay_reason,'deliverable_url',new.deliverable_url,'acceptance_criteria',new.acceptance_criteria))
    on conflict do nothing;
  end if;
  return new;
end $$;
revoke all on function harim_nexus_private.p1_task_events(),harim_nexus_private.p1_task_stamp() from public,anon,authenticated;

-- 서버 API 전용: 점검 답변 저장과 업무 완료를 한 트랜잭션으로.
create or replace function harim_nexus.nexus_submit_completion_check(p_id bigint,p_member bigint,p_answers jsonb)
returns harim_nexus.task_completion_checks language plpgsql security invoker set search_path='' as $$
declare c harim_nexus.task_completion_checks; t harim_nexus.tasks;
begin
  select * into c from harim_nexus.task_completion_checks where id=p_id and member_id=p_member for update;
  if c.id is null then raise exception '내 완료 점검만 제출할 수 있습니다.'; end if;
  if c.status<>'draft' then raise exception '이미 제출했거나 닫힌 점검입니다. 완료 버튼을 다시 눌러 주세요.'; end if;
  if jsonb_typeof(p_answers) is distinct from 'array' or jsonb_array_length(p_answers)<>jsonb_array_length(c.questions) then raise exception '모든 질문에 답해 주세요.'; end if;
  if exists(select 1 from jsonb_array_elements(p_answers) a where jsonb_typeof(a)<>'string' or length(trim(a#>>'{}')) not between 1 and 3000) then
    raise exception '답변은 질문마다 1~3000자로 적어 주세요.';
  end if;
  select * into t from harim_nexus.tasks where id=c.task_id and workspace_id=c.workspace_id for update;
  if t.id is null or t.deleted_at is not null then raise exception '삭제되었거나 찾을 수 없는 업무입니다.'; end if;
  if t.status='완료' then raise exception '이미 완료된 업무입니다.'; end if;
  update harim_nexus.task_completion_checks set status='superseded' where task_id=c.task_id and status in ('draft','submitted') and id<>c.id;
  update harim_nexus.task_completion_checks set
    answers=(select jsonb_agg(trim(a.value#>>'{}') order by a.ord) from jsonb_array_elements(p_answers) with ordinality a(value,ord)),
    status='submitted', submitted_at=now()
  where id=p_id returning * into c;
  perform set_config('harim_nexus.actor', p_member::text, true);
  update harim_nexus.tasks set status='완료' where id=t.id;
  return c;
end $$;

-- 서버 API 전용(관리자 확인 후 호출): 확인 완료 또는 보완 요청(업무를 진행중으로 되돌림).
create or replace function harim_nexus.nexus_review_completion_check(p_id bigint,p_reviewer bigint,p_action text,p_comment text default null)
returns harim_nexus.task_completion_checks language plpgsql security invoker set search_path='' as $$
declare c harim_nexus.task_completion_checks; task_title text; note text;
begin
  if p_action not in ('approve','return') then raise exception '잘못된 검토 요청입니다.'; end if;
  note := nullif(trim(coalesce(p_comment,'')),'');
  if p_action='return' and note is null then raise exception '보완할 내용을 적어 주세요.'; end if;
  if length(coalesce(note,''))>3000 then raise exception '의견은 3000자 이내로 적어 주세요.'; end if;
  select * into c from harim_nexus.task_completion_checks where id=p_id for update;
  if c.id is null then raise exception '점검 기록을 찾을 수 없습니다.'; end if;
  if c.status<>'submitted' then raise exception '검토 대기 중인 점검이 아닙니다. 새로고침해 주세요.'; end if;
  update harim_nexus.task_completion_checks set status=case when p_action='approve' then 'approved' else 'returned' end,
    lead_comment=note, reviewed_by_member_id=p_reviewer, reviewed_at=now()
  where id=p_id returning * into c;
  select title into task_title from harim_nexus.tasks where id=c.task_id;
  if p_action='return' then
    perform set_config('harim_nexus.actor', p_reviewer::text, true);
    update harim_nexus.tasks set status='진행중' where id=c.task_id and status='완료' and deleted_at is null;
  end if;
  if c.member_id<>p_reviewer then
    insert into harim_nexus.notifications(workspace_id,recipient_member_id,actor_member_id,kind,title,body,entity_type,entity_id,action_url)
    values(c.workspace_id,c.member_id,p_reviewer,case when p_action='approve' then 'status' else 'system' end,
      case when p_action='approve' then '팀장이 완료 점검을 확인했습니다: ' else '완료 점검 보완 요청: ' end||coalesce(task_title,''),
      left(coalesce(note,''),240),'completion_check',c.id::text,'/ai?check='||c.id);
  end if;
  return c;
end $$;

-- 완료 점검 질문용 호출 예약 (검토 행 없이 회원 기준으로 일·월 한도 확인)
create or replace function harim_nexus.nexus_reserve_member_ai_call(p_workspace uuid,p_member bigint,p_tokens bigint)
returns bigint language plpgsql security invoker set search_path='' as $$
declare s harim_nexus.workspace_settings; used bigint; calls bigint; call_id bigint;
begin
  select * into s from harim_nexus.workspace_settings where workspace_id=p_workspace for update;
  if not coalesce(s.ai_enabled,false) then raise exception '관리자가 AI 외부 전송을 활성화해야 합니다.'; end if;
  select count(*) into calls from harim_nexus.ai_call_usage where workspace_id=p_workspace and member_id=p_member and created_at >= (date_trunc('day',now() at time zone 'Asia/Seoul') at time zone 'Asia/Seoul');
  select coalesce(sum(coalesce(input_tokens+output_tokens,reserved_tokens)),0) into used from harim_nexus.ai_call_usage where workspace_id=p_workspace and created_at >= (date_trunc('month',now() at time zone 'Asia/Seoul') at time zone 'Asia/Seoul');
  if calls>=s.ai_daily_limit then raise exception '오늘의 AI 호출 상한에 도달했습니다.'; end if;
  if p_tokens<1 or used+p_tokens>s.ai_monthly_token_budget then raise exception '월 AI 토큰 예산이 부족합니다.'; end if;
  insert into harim_nexus.ai_call_usage(workspace_id,member_id,review_id,reserved_tokens) values(p_workspace,p_member,null,p_tokens) returning id into call_id;
  return call_id;
end $$;

revoke all on function harim_nexus.nexus_submit_completion_check(bigint,bigint,jsonb),harim_nexus.nexus_review_completion_check(bigint,bigint,text,text),harim_nexus.nexus_reserve_member_ai_call(uuid,bigint,bigint) from public,anon,authenticated;
grant execute on function harim_nexus.nexus_submit_completion_check(bigint,bigint,jsonb),harim_nexus.nexus_review_completion_check(bigint,bigint,text,text),harim_nexus.nexus_reserve_member_ai_call(uuid,bigint,bigint) to service_role;
notify pgrst,'reload schema';
commit;
