-- 05: 내 작업공간(일일 업무 기록) + 비서몬 이름 반영
-- 01~04 적용 후 SQL Editor 에서 실행. 다시 실행해도 안전. public/Auth/Storage 는 변경하지 않는다.
-- 일일 기록은 본인만 본다(팀장도 볼 수 없음). 저장·조회는 서버 라우트(service_role)가 본인 확인 후 처리한다.
begin;

create table if not exists harim_nexus.daily_logs (
  id bigint generated by default as identity primary key,
  workspace_id uuid not null references harim_nexus.workspaces(id) on delete cascade,
  member_id bigint not null references harim_nexus.members(id) on delete cascade,
  log_date date not null,
  content text not null check (length(content) between 1 and 8000),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique(workspace_id, member_id, log_date)
);
create index if not exists idx_daily_logs_member_date on harim_nexus.daily_logs(workspace_id,member_id,log_date desc);

alter table harim_nexus.daily_logs enable row level security;
revoke all on harim_nexus.daily_logs from public,anon,authenticated;
grant select on harim_nexus.daily_logs to authenticated;
grant all on harim_nexus.daily_logs to service_role;
grant usage,select on sequence harim_nexus.daily_logs_id_seq to service_role;
drop policy if exists daily_logs_read_own on harim_nexus.daily_logs;
create policy daily_logs_read_own on harim_nexus.daily_logs for select to authenticated using (
  harim_nexus_private.has_workspace_access(workspace_id,null) and member_id = harim_nexus_private.current_nexus_member_id()
);

-- 04 의 완료 가드 문구만 "비서몬"으로 바꾼다 (동작은 04 와 동일)
create or replace function harim_nexus_private.p1_task_stamp()
returns trigger language plpgsql security invoker set search_path='' as $$
begin
  if new.status='완료' and (tg_op='INSERT' or old.status is distinct from '완료') and current_user='authenticated' then
    raise exception '비서몬 완료 점검을 거쳐야 완료할 수 있습니다. 화면을 새로고침한 뒤 완료 버튼을 다시 눌러 주세요.' using errcode='P0001';
  end if;
  new.updated_at := clock_timestamp();
  if tg_op='INSERT' then
    new.completed_at := case when new.status='완료' then now() else null end;
    new.requested_by_member_id := coalesce(harim_nexus_private.current_nexus_member_id(),new.created_by_member_id);
  else
    if new.status is distinct from old.status then
      new.completed_at := case when new.status='완료' then now() else null end;
    else new.completed_at := old.completed_at;
    end if;
    if new.assignee_member_id is distinct from old.assignee_member_id then
      new.requested_by_member_id := coalesce(harim_nexus_private.current_nexus_member_id(),new.created_by_member_id);
      new.accepted_at := null;
    else new.requested_by_member_id := old.requested_by_member_id;
    end if;
  end if;
  return new;
end $$;

notify pgrst,'reload schema';
commit;
